var searchData=
[
  ['a_20base_20class_20and_20templated_20child_20class_0',['Using a base class and templated child class',['../registered_type_page.html#implement_templated_registered_type_two_class',1,'']]],
  ['a_20custom_20type_20name_1',['How to implement a RegisteredType with a custom type name',['../registered_type_page.html#using_registered_subclass_with_typename',1,'']]],
  ['a_20new_20neurodata_20type_2',['Implementing a new Neurodata Type',['../registered_type_page.html',1,'devdocs']]],
  ['a_20new_20type_3',['Example: Implementing a new type',['../registered_type_page.html#implement_registered_type_example',1,'']]],
  ['a_20recording_20workflow_4',['Overview of a recording workflow',['../workflow.html#recording_workflow',1,'']]],
  ['a_20registeredtype_5',['How to Implement a RegisteredType',['../registered_type_page.html#implement_registered_type',1,'']]],
  ['a_20registeredtype_20with_20a_20custom_20type_20name_6',['How to implement a RegisteredType with a custom type name',['../registered_type_page.html#using_registered_subclass_with_typename',1,'']]],
  ['a_20single_20templated_20class_7',['Using a single templated class',['../registered_type_page.html#implement_templated_registered_type_single_class',1,'']]],
  ['acquiring_20data_8',['Acquiring Data',['../workflow.html',1,'userdocs']]],
  ['add_20to_20recordingcontainers_9',['5. Create datasets and add to RecordingContainers.',['../workflow.html#create_datasets',1,'']]],
  ['addcolumn_10',['addColumn',['../class_a_q_n_w_b_1_1_n_w_b_1_1_dynamic_table.html#a916169b9c8b324833861df2af1b59c3f',1,'AQNWB::NWB::DynamicTable']]],
  ['addcontainer_11',['addContainer',['../class_a_q_n_w_b_1_1_n_w_b_1_1_recording_containers.html#a446ec0d5f5e7802d9e44725399c71e8c',1,'AQNWB::NWB::RecordingContainers']]],
  ['addelectrodes_12',['addElectrodes',['../class_a_q_n_w_b_1_1_n_w_b_1_1_electrode_table.html#a41f29ce1a76fd932eac4a03e67d8268f',1,'AQNWB::NWB::ElectrodeTable']]],
  ['addfilter_13',['addFilter',['../class_a_q_n_w_b_1_1_i_o_1_1_h_d_f5_1_1_h_d_f5_array_data_set_config.html#a9aefd3b9c5e9fd7efcdb2950e63e557b',1,'AQNWB::IO::HDF5::HDF5ArrayDataSetConfig::addFilter(H5Z_filter_t filter_id, const std::vector&lt; unsigned int &gt; &amp;cd_values)'],['../class_a_q_n_w_b_1_1_i_o_1_1_h_d_f5_1_1_h_d_f5_array_data_set_config.html#af7a55a42c9cab51fe6a59abc5dfed5ef',1,'AQNWB::IO::HDF5::HDF5ArrayDataSetConfig::addFilter(const HDF5FilterConfig &amp;filter)']]],
  ['addfilters_14',['addFilters',['../class_a_q_n_w_b_1_1_i_o_1_1_h_d_f5_1_1_h_d_f5_array_data_set_config.html#accb494cb492b3a33526ab81f3a578320',1,'AQNWB::IO::HDF5::HDF5ArrayDataSetConfig']]],
  ['addreferencecolumn_15',['addReferenceColumn',['../class_a_q_n_w_b_1_1_n_w_b_1_1_dynamic_table.html#ab5d214fb6eb95bcaf0f4988b12e2b2db',1,'AQNWB::NWB::DynamicTable']]],
  ['an_20existing_20file_20for_20reading_16',['Opening an existing file for reading',['../read_page.html#read_example_open',1,'']]],
  ['an_20nwb_20file_20with_20swmr_20mode_17',['Writing an NWB file with SWMR mode',['../hdf5io.html#hdf5io_swmr_workflow',1,'']]],
  ['and_20add_20to_20recordingcontainers_18',['5. Create datasets and add to RecordingContainers.',['../workflow.html#create_datasets',1,'']]],
  ['and_20attributes_19',['and attributes',['../registered_type_page.html#use_the_define_field_macro',1,'DEFINE_FIELD: Creating read methods for datasets and attributes'],['../read_design_page.html#read_design_sec_read_date',1,'Reading datasets and attributes']]],
  ['and_20compression_20',['I/O Filters and Compression',['../hdf5io.html#hdf5io_filters',1,'']]],
  ['and_20finalize_20the_20file_21',['8. Stop the recording and finalize the file.',['../workflow.html#stop_recording',1,'']]],
  ['and_20i_20o_20filters_20in_20aqnwb_22',['Using Chunking and I/O Filters in AqNWB',['../hdf5io.html#hdf5io_filters_usage',1,'']]],
  ['and_20processing_20data_23',['Reading and Processing Data',['../read_design_page.html#read_design_example_read',1,'']]],
  ['and_20templated_20child_20class_24',['Using a base class and templated child class',['../registered_type_page.html#implement_templated_registered_type_two_class',1,'']]],
  ['and_20test_25',['Configure, Build and Test',['../dev_install_page.html#configure_build_test',1,'']]],
  ['and_20writing_20data_26',['Creating and Writing Data',['../read_design_page.html#read_design_example_create',1,'']]],
  ['annotationseries_27',['AnnotationSeries',['../class_a_q_n_w_b_1_1_n_w_b_1_1_annotation_series.html',1,'AQNWB::NWB::AnnotationSeries'],['../class_a_q_n_w_b_1_1_n_w_b_1_1_annotation_series.html#ab98f231850a75a82fade2234e8606359',1,'AQNWB::NWB::AnnotationSeries::AnnotationSeries()']]],
  ['annotationseries_2ecpp_28',['AnnotationSeries.cpp',['../_annotation_series_8cpp.html',1,'']]],
  ['annotationseries_2ehpp_29',['AnnotationSeries.hpp',['../_annotation_series_8hpp.html',1,'']]],
  ['aqnwb_30',['AQNWB',['../namespace_a_q_n_w_b.html',1,'']]],
  ['aqnwb_31',['AqNWB',['../user_install_page.html',1,'Installing AqNWB'],['../hdf5io.html#hdf5io_filters_usage',1,'Using Chunking and I/O Filters in AqNWB']]],
  ['aqnwb_20use_20smwr_20mode_32',['Why does AqNWB use SMWR mode?',['../hdf5io.html#hdf5io_swmr_features',1,'']]],
  ['aqnwb_3a_3ahdf5_33',['HDF5',['../namespace_a_q_n_w_b_1_1_h_d_f5.html',1,'AQNWB']]],
  ['aqnwb_3a_3aio_34',['IO',['../namespace_a_q_n_w_b_1_1_i_o.html',1,'AQNWB']]],
  ['aqnwb_3a_3aio_3a_3ahdf5_35',['HDF5',['../namespace_a_q_n_w_b_1_1_i_o_1_1_h_d_f5.html',1,'AQNWB::IO']]],
  ['aqnwb_3a_3anwb_36',['NWB',['../namespace_a_q_n_w_b_1_1_n_w_b.html',1,'AQNWB']]],
  ['aqnwb_3a_3aspec_37',['SPEC',['../namespace_a_q_n_w_b_1_1_s_p_e_c.html',1,'AQNWB']]],
  ['aqnwb_3a_3aspec_3a_3acore_38',['CORE',['../namespace_a_q_n_w_b_1_1_s_p_e_c_1_1_c_o_r_e.html',1,'AQNWB::SPEC']]],
  ['aqnwb_3a_3aspec_3a_3ahdmf_5fcommon_39',['HDMF_COMMON',['../namespace_a_q_n_w_b_1_1_s_p_e_c_1_1_h_d_m_f___c_o_m_m_o_n.html',1,'AQNWB::SPEC']]],
  ['aqnwb_3a_3aspec_3a_3ahdmf_5fexperimental_40',['HDMF_EXPERIMENTAL',['../namespace_a_q_n_w_b_1_1_s_p_e_c_1_1_h_d_m_f___e_x_p_e_r_i_m_e_n_t_a_l.html',1,'AQNWB::SPEC']]],
  ['arbitrary_20fields_41',['Reading arbitrary fields',['../read_page.html#read_example_arbitrary',1,'']]],
  ['arraydatasetconfig_42',['ArrayDataSetConfig',['../class_a_q_n_w_b_1_1_i_o_1_1_array_data_set_config.html',1,'AQNWB::IO::ArrayDataSetConfig'],['../class_a_q_n_w_b_1_1_i_o_1_1_array_data_set_config.html#abe5aa8c2e9f5d7ad2a0ca4da2d7d5fd9',1,'AQNWB::IO::ArrayDataSetConfig::ArrayDataSetConfig()']]],
  ['as_5fmulti_5farray_43',['as_multi_array',['../class_a_q_n_w_b_1_1_i_o_1_1_data_block.html#a39c4d437721b818aac335f3c9a57dc97',1,'AQNWB::IO::DataBlock']]],
  ['as_5fvariant_44',['as_variant',['../class_a_q_n_w_b_1_1_i_o_1_1_data_block_generic.html#a957ab6f55f6be707def1ae317948a6eb',1,'AQNWB::IO::DataBlockGeneric']]],
  ['attribute_45',['Attribute',['../class_a_q_n_w_b_1_1_types.html#a778ba605df5dabb117ede12e41111915a459ad320d6c923a4111734767c71b20c',1,'AQNWB::Types']]],
  ['attributeexists_46',['attributeExists',['../class_a_q_n_w_b_1_1_i_o_1_1_base_i_o.html#a06b5edf2bbd4c85adcafda13e7903873',1,'AQNWB::IO::BaseIO::attributeExists()'],['../class_a_q_n_w_b_1_1_i_o_1_1_h_d_f5_1_1_h_d_f5_i_o.html#a53bfbbdbf24afdd97ea45294b65c1e37',1,'AQNWB::IO::HDF5::HDF5IO::attributeExists()']]],
  ['attributefield_47',['AttributeField',['../namespace_a_q_n_w_b_1_1_n_w_b.html#a4a7413b10eb1a838f0349fc59b5a333f',1,'AQNWB::NWB']]],
  ['attributes_48',['attributes',['../registered_type_page.html#use_the_define_field_macro',1,'DEFINE_FIELD: Creating read methods for datasets and attributes'],['../read_design_page.html#read_design_sec_read_date',1,'Reading datasets and attributes']]],
  ['automated_20tests_20on_20github_49',['Automated tests on GitHub',['../testing.html#testing_github',1,'']]]
];
