var searchData=
[
  ['a_20new_20neurodata_20type_0',['Implementing a new Neurodata Type',['../registered_type_page.html',1,'devdocs']]],
  ['a_20new_20type_1',['Example: Implementing a new type',['../registered_type_page.html#implement_registered_type_example',1,'']]],
  ['a_20nwb_20file_20as_20usual_2',['Create a NWB file as usual',['../read_page.html#read_design_example_create',1,'']]],
  ['a_20recording_20workflow_3',['Overview of a recording workflow',['../workflow.html#recording_workflow',1,'']]],
  ['a_20registeredtype_4',['How to Implement a RegisteredType',['../registered_type_page.html#implement_registered_type',1,'']]],
  ['access_5',['Lazy data access',['../read_page.html#read_design_example_lazy_read',1,'']]],
  ['accessing_20multi_20dimensional_20data_20as_20boost_20multi_20array_6',['Accessing multi-dimensional data as Boost multi-array',['../read_page.html#read_design_example_boostarray',1,'']]],
  ['acquiring_20data_7',['Acquiring Data',['../workflow.html',1,'userdocs']]],
  ['acquisitionpath_8',['acquisitionPath',['../class_a_q_n_w_b_1_1_n_w_b_1_1_n_w_b_file.html#a83b0703a52e9d9ffc3c6832497c2e921',1,'AQNWB::NWB::NWBFile']]],
  ['add_20to_20recordingcontainers_9',['4. Create datasets and add to RecordingContainers.',['../workflow.html#create_datasets',1,'']]],
  ['addcolumn_10',['addColumn',['../class_a_q_n_w_b_1_1_n_w_b_1_1_dynamic_table.html#a1ceca036a944163395217a28c8278da8',1,'AQNWB::NWB::DynamicTable']]],
  ['addcontainer_11',['addContainer',['../class_a_q_n_w_b_1_1_n_w_b_1_1_recording_containers.html#a446ec0d5f5e7802d9e44725399c71e8c',1,'AQNWB::NWB::RecordingContainers']]],
  ['addelectrodes_12',['addElectrodes',['../class_a_q_n_w_b_1_1_n_w_b_1_1_electrode_table.html#a41f29ce1a76fd932eac4a03e67d8268f',1,'AQNWB::NWB::ElectrodeTable']]],
  ['addreferencecolumn_13',['addReferenceColumn',['../class_a_q_n_w_b_1_1_n_w_b_1_1_dynamic_table.html#af693d1a0af16ec266645ecd696afef24',1,'AQNWB::NWB::DynamicTable']]],
  ['an_20attribute_14',['Reading an attribute',['../read_page.html#read_design_example_attribute',1,'']]],
  ['an_20existing_20file_15',['Reading from an existing file',['../read_page.html#read_design_example_read_from_existing_file',1,'']]],
  ['an_20existing_20file_20for_20reading_16',['Opening an existing file for reading',['../read_page.html#read_design_example_read_create_io',1,'']]],
  ['an_20nwb_20file_20with_20swmr_20mode_17',['Writing an NWB file with SWMR mode',['../hdf5io.html#hdf5io_swmr_workflow',1,'']]],
  ['and_20add_20to_20recordingcontainers_18',['4. Create datasets and add to RecordingContainers.',['../workflow.html#create_datasets',1,'']]],
  ['and_20attributes_19',['Reading Datasets and Attributes',['../read_page.html#read_design_example_read_during',1,'']]],
  ['and_20attributes_20',['Reading datasets and attributes',['../read_page.html#read_design_sec_read_date',1,'']]],
  ['and_20datablock_21',['DataBlockGeneric and DataBlock',['../read_page.html#read_design_data_block',1,'']]],
  ['and_20finalize_20the_20file_22',['7. Stop the recording and finalize the file.',['../workflow.html#stop_recording',1,'']]],
  ['and_20record_20data_23',['Create the NWBFile and record data',['../read_page.html#read_design_example_step_1_2',1,'']]],
  ['and_20test_24',['Configure, Build and Test',['../dev_install_page.html#configure_build_test',1,'']]],
  ['aqnwb_25',['AQNWB',['../namespace_a_q_n_w_b.html',1,'']]],
  ['aqnwb_26',['Installing AqNWB',['../user_install_page.html',1,'userdocs']]],
  ['aqnwb_20use_20smwr_20mode_27',['Why does AqNWB use SMWR mode?',['../hdf5io.html#hdf5io_swmr_features',1,'']]],
  ['aqnwb_3a_3ahdf5_28',['HDF5',['../namespace_a_q_n_w_b_1_1_h_d_f5.html',1,'AQNWB']]],
  ['aqnwb_3a_3aio_29',['IO',['../namespace_a_q_n_w_b_1_1_i_o.html',1,'AQNWB']]],
  ['aqnwb_3a_3aio_3a_3ahdf5_30',['HDF5',['../namespace_a_q_n_w_b_1_1_i_o_1_1_h_d_f5.html',1,'AQNWB::IO']]],
  ['aqnwb_3a_3anwb_31',['NWB',['../namespace_a_q_n_w_b_1_1_n_w_b.html',1,'AQNWB']]],
  ['aqnwb_3a_3aspec_32',['SPEC',['../namespace_a_q_n_w_b_1_1_s_p_e_c.html',1,'AQNWB']]],
  ['aqnwb_3a_3aspec_3a_3acore_33',['CORE',['../namespace_a_q_n_w_b_1_1_s_p_e_c_1_1_c_o_r_e.html',1,'AQNWB::SPEC']]],
  ['aqnwb_3a_3aspec_3a_3ahdmf_5fcommon_34',['HDMF_COMMON',['../namespace_a_q_n_w_b_1_1_s_p_e_c_1_1_h_d_m_f___c_o_m_m_o_n.html',1,'AQNWB::SPEC']]],
  ['aqnwb_3a_3aspec_3a_3ahdmf_5fexperimental_35',['HDMF_EXPERIMENTAL',['../namespace_a_q_n_w_b_1_1_s_p_e_c_1_1_h_d_m_f___e_x_p_e_r_i_m_e_n_t_a_l.html',1,'AQNWB::SPEC']]],
  ['array_36',['Accessing multi-dimensional data as Boost multi-array',['../read_page.html#read_design_example_boostarray',1,'']]],
  ['array_20for_20n_20dimensional_20data_37',['Using Boost Multi Array for N-Dimensional Data',['../read_page.html#read_design_data_block_multiarray',1,'']]],
  ['as_20boost_20multi_20array_38',['Accessing multi-dimensional data as Boost multi-array',['../read_page.html#read_design_example_boostarray',1,'']]],
  ['as_20usual_39',['Create a NWB file as usual',['../read_page.html#read_design_example_create',1,'']]],
  ['as_5fmulti_5farray_40',['as_multi_array',['../class_a_q_n_w_b_1_1_i_o_1_1_data_block.html#a39c4d437721b818aac335f3c9a57dc97',1,'AQNWB::IO::DataBlock']]],
  ['attribute_41',['Attribute',['../class_a_q_n_w_b_1_1_types.html#a778ba605df5dabb117ede12e41111915a459ad320d6c923a4111734767c71b20c',1,'AQNWB::Types']]],
  ['attribute_42',['Reading an attribute',['../read_page.html#read_design_example_attribute',1,'']]],
  ['attributeexists_43',['attributeExists',['../class_a_q_n_w_b_1_1_i_o_1_1_base_i_o.html#a06b5edf2bbd4c85adcafda13e7903873',1,'AQNWB::IO::BaseIO::attributeExists()'],['../class_a_q_n_w_b_1_1_i_o_1_1_h_d_f5_1_1_h_d_f5_i_o.html#a53bfbbdbf24afdd97ea45294b65c1e37',1,'AQNWB::IO::HDF5::HDF5IO::attributeExists()']]],
  ['attributefield_44',['AttributeField',['../namespace_a_q_n_w_b_1_1_n_w_b.html#a4a7413b10eb1a838f0349fc59b5a333f',1,'AQNWB::NWB']]],
  ['attributes_45',['Reading Datasets and Attributes',['../read_page.html#read_design_example_read_during',1,'']]],
  ['attributes_46',['Reading datasets and attributes',['../read_page.html#read_design_sec_read_date',1,'']]],
  ['automated_20tests_20on_20github_47',['Automated tests on GitHub',['../testing.html#testing_github',1,'']]]
];
