var searchData=
[
  ['a_20custom_20type_20name_0',['How to implement a RegisteredType with a custom type name',['../registered_type_page.html#using_registered_subclass_with_typename',1,'']]],
  ['a_20new_20neurodata_20type_1',['Implementing a new Neurodata Type',['../registered_type_page.html',1,'devdocs']]],
  ['a_20new_20type_2',['Example: Implementing a new type',['../registered_type_page.html#implement_registered_type_example',1,'']]],
  ['a_20recording_20workflow_3',['Overview of a recording workflow',['../workflow.html#recording_workflow',1,'']]],
  ['a_20registeredtype_4',['How to Implement a RegisteredType',['../registered_type_page.html#implement_registered_type',1,'']]],
  ['a_20registeredtype_20with_20a_20custom_20type_20name_5',['How to implement a RegisteredType with a custom type name',['../registered_type_page.html#using_registered_subclass_with_typename',1,'']]],
  ['acquiring_20data_6',['Acquiring Data',['../workflow.html',1,'userdocs']]],
  ['acquisitionpath_7',['acquisitionPath',['../class_a_q_n_w_b_1_1_n_w_b_1_1_n_w_b_file.html#a83b0703a52e9d9ffc3c6832497c2e921',1,'AQNWB::NWB::NWBFile']]],
  ['add_20to_20recordingcontainers_8',['4. Create datasets and add to RecordingContainers.',['../workflow.html#create_datasets',1,'']]],
  ['addcolumn_9',['addColumn',['../class_a_q_n_w_b_1_1_n_w_b_1_1_dynamic_table.html#af66cd6ab358788b75dc0b778d08bdca3',1,'AQNWB::NWB::DynamicTable']]],
  ['addcontainer_10',['addContainer',['../class_a_q_n_w_b_1_1_n_w_b_1_1_recording_containers.html#a446ec0d5f5e7802d9e44725399c71e8c',1,'AQNWB::NWB::RecordingContainers']]],
  ['addelectrodes_11',['addElectrodes',['../class_a_q_n_w_b_1_1_n_w_b_1_1_electrode_table.html#a41f29ce1a76fd932eac4a03e67d8268f',1,'AQNWB::NWB::ElectrodeTable']]],
  ['addreferencecolumn_12',['addReferenceColumn',['../class_a_q_n_w_b_1_1_n_w_b_1_1_dynamic_table.html#ab5d214fb6eb95bcaf0f4988b12e2b2db',1,'AQNWB::NWB::DynamicTable']]],
  ['an_20existing_20file_20for_20reading_13',['Opening an existing file for reading',['../read_page.html#read_example_open',1,'']]],
  ['an_20nwb_20file_20with_20swmr_20mode_14',['Writing an NWB file with SWMR mode',['../hdf5io.html#hdf5io_swmr_workflow',1,'']]],
  ['and_20add_20to_20recordingcontainers_15',['4. Create datasets and add to RecordingContainers.',['../workflow.html#create_datasets',1,'']]],
  ['and_20attributes_16',['and attributes',['../registered_type_page.html#use_the_define_field_macro',1,'DEFINE_FIELD: Creating read methods for datasets and attributes'],['../read_design_page.html#read_design_sec_read_date',1,'Reading datasets and attributes']]],
  ['and_20finalize_20the_20file_17',['7. Stop the recording and finalize the file.',['../workflow.html#stop_recording',1,'']]],
  ['and_20processing_20data_18',['Reading and Processing Data',['../read_design_page.html#read_design_example_read',1,'']]],
  ['and_20test_19',['Configure, Build and Test',['../dev_install_page.html#configure_build_test',1,'']]],
  ['and_20writing_20data_20',['Creating and Writing Data',['../read_design_page.html#read_design_example_create',1,'']]],
  ['annotationseries_21',['AnnotationSeries',['../class_a_q_n_w_b_1_1_n_w_b_1_1_annotation_series.html',1,'AQNWB::NWB::AnnotationSeries'],['../class_a_q_n_w_b_1_1_n_w_b_1_1_annotation_series.html#ab98f231850a75a82fade2234e8606359',1,'AQNWB::NWB::AnnotationSeries::AnnotationSeries()']]],
  ['annotationseries_2ecpp_22',['AnnotationSeries.cpp',['../_annotation_series_8cpp.html',1,'']]],
  ['annotationseries_2ehpp_23',['AnnotationSeries.hpp',['../_annotation_series_8hpp.html',1,'']]],
  ['aqnwb_24',['AQNWB',['../namespace_a_q_n_w_b.html',1,'']]],
  ['aqnwb_25',['Installing AqNWB',['../user_install_page.html',1,'userdocs']]],
  ['aqnwb_20use_20smwr_20mode_26',['Why does AqNWB use SMWR mode?',['../hdf5io.html#hdf5io_swmr_features',1,'']]],
  ['aqnwb_3a_3ahdf5_27',['HDF5',['../namespace_a_q_n_w_b_1_1_h_d_f5.html',1,'AQNWB']]],
  ['aqnwb_3a_3aio_28',['IO',['../namespace_a_q_n_w_b_1_1_i_o.html',1,'AQNWB']]],
  ['aqnwb_3a_3aio_3a_3ahdf5_29',['HDF5',['../namespace_a_q_n_w_b_1_1_i_o_1_1_h_d_f5.html',1,'AQNWB::IO']]],
  ['aqnwb_3a_3anwb_30',['NWB',['../namespace_a_q_n_w_b_1_1_n_w_b.html',1,'AQNWB']]],
  ['aqnwb_3a_3aspec_31',['SPEC',['../namespace_a_q_n_w_b_1_1_s_p_e_c.html',1,'AQNWB']]],
  ['aqnwb_3a_3aspec_3a_3acore_32',['CORE',['../namespace_a_q_n_w_b_1_1_s_p_e_c_1_1_c_o_r_e.html',1,'AQNWB::SPEC']]],
  ['aqnwb_3a_3aspec_3a_3ahdmf_5fcommon_33',['HDMF_COMMON',['../namespace_a_q_n_w_b_1_1_s_p_e_c_1_1_h_d_m_f___c_o_m_m_o_n.html',1,'AQNWB::SPEC']]],
  ['aqnwb_3a_3aspec_3a_3ahdmf_5fexperimental_34',['HDMF_EXPERIMENTAL',['../namespace_a_q_n_w_b_1_1_s_p_e_c_1_1_h_d_m_f___e_x_p_e_r_i_m_e_n_t_a_l.html',1,'AQNWB::SPEC']]],
  ['arbitrary_20fields_35',['Reading arbitrary fields',['../read_page.html#read_example_arbitrary',1,'']]],
  ['as_5fmulti_5farray_36',['as_multi_array',['../class_a_q_n_w_b_1_1_i_o_1_1_data_block.html#a39c4d437721b818aac335f3c9a57dc97',1,'AQNWB::IO::DataBlock']]],
  ['attribute_37',['Attribute',['../class_a_q_n_w_b_1_1_types.html#a778ba605df5dabb117ede12e41111915a459ad320d6c923a4111734767c71b20c',1,'AQNWB::Types']]],
  ['attributeexists_38',['attributeExists',['../class_a_q_n_w_b_1_1_i_o_1_1_base_i_o.html#a06b5edf2bbd4c85adcafda13e7903873',1,'AQNWB::IO::BaseIO::attributeExists()'],['../class_a_q_n_w_b_1_1_i_o_1_1_h_d_f5_1_1_h_d_f5_i_o.html#a53bfbbdbf24afdd97ea45294b65c1e37',1,'AQNWB::IO::HDF5::HDF5IO::attributeExists()']]],
  ['attributefield_39',['AttributeField',['../namespace_a_q_n_w_b_1_1_n_w_b.html#a4a7413b10eb1a838f0349fc59b5a333f',1,'AQNWB::NWB']]],
  ['attributes_40',['attributes',['../registered_type_page.html#use_the_define_field_macro',1,'DEFINE_FIELD: Creating read methods for datasets and attributes'],['../read_design_page.html#read_design_sec_read_date',1,'Reading datasets and attributes']]],
  ['automated_20tests_20on_20github_41',['Automated tests on GitHub',['../testing.html#testing_github',1,'']]]
];
