var searchData=
[
  ['data_0',['Data',['../workflow.html',1,'Acquiring Data'],['../class_a_q_n_w_b_1_1_n_w_b_1_1_data.html',1,'AQNWB::NWB::Data&lt; DTYPE &gt;'],['../class_a_q_n_w_b_1_1_n_w_b_1_1_data.html#ad1917750d0ee4cdd9801ccfc15084b84',1,'AQNWB::NWB::Data::Data()'],['../read_page.html#read_design_data_block_multiarray',1,'Using Boost Multi Array for N-Dimensional Data']]],
  ['data_1',['data',['../workflow.html#write_data',1,'6. Write data.'],['../read_page.html#read_design_example_step_1_2',1,'Create the NWBFile and record data'],['../class_a_q_n_w_b_1_1_i_o_1_1_data_block_generic.html#a7c75a76906f183f7cc79be020823722e',1,'AQNWB::IO::DataBlockGeneric::data'],['../class_a_q_n_w_b_1_1_i_o_1_1_data_block.html#a7e084bd163c177f45c41cdf93b61f2b6',1,'AQNWB::IO::DataBlock::data'],['../class_a_q_n_w_b_1_1_n_w_b_1_1_time_series.html#a5ad16f8a582e49ca4f57bbc3a98217a0',1,'AQNWB::NWB::TimeSeries::data'],['../read_page.html#read_design_data_block_typed',1,'DataBlock with typed data'],['../read_page.html',1,'Reading data']]],
  ['data_20access_2',['Lazy data access',['../read_page.html#read_design_example_lazy_read',1,'']]],
  ['data_20as_20boost_20multi_20array_3',['Accessing multi-dimensional data as Boost multi-array',['../read_page.html#read_design_example_boostarray',1,'']]],
  ['data_20fields_4',['Reading data fields',['../read_page.html#read_design_example_read_posthoc_read_field',1,'']]],
  ['data_20for_20write_5',['Setup mock data for write',['../read_page.html#read_design_example_step_1',1,'']]],
  ['data_20into_20memory_6',['Read data into memory',['../read_page.html#read_design_example_load_data',1,'']]],
  ['data_20with_20unknown_20type_7',['Reading data with unknown type',['../read_page.html#read_design_example_readgeneric',1,'']]],
  ['data_2ecpp_8',['Data.cpp',['../_data_8cpp.html',1,'']]],
  ['data_2ehpp_9',['Data.hpp',['../_data_8hpp.html',1,'']]],
  ['data_3c_20int_20_3e_10',['Data&lt; int &gt;',['../class_a_q_n_w_b_1_1_n_w_b_1_1_data.html',1,'AQNWB::NWB']]],
  ['data_3c_20std_3a_3aany_20_3e_11',['Data&lt; std::any &gt;',['../class_a_q_n_w_b_1_1_n_w_b_1_1_data.html',1,'AQNWB::NWB']]],
  ['datablock_12',['DataBlock',['../class_a_q_n_w_b_1_1_i_o_1_1_data_block.html',1,'AQNWB::IO::DataBlock&lt; DTYPE &gt;'],['../class_a_q_n_w_b_1_1_i_o_1_1_data_block.html#a19215d8fade24ca715da77a234766059',1,'AQNWB::IO::DataBlock::DataBlock()'],['../read_page.html#read_design_data_block',1,'DataBlockGeneric and DataBlock']]],
  ['datablock_20with_20typed_20data_13',['DataBlock with typed data',['../read_page.html#read_design_data_block_typed',1,'']]],
  ['datablockgeneric_14',['DataBlockGeneric',['../class_a_q_n_w_b_1_1_i_o_1_1_data_block_generic.html',1,'AQNWB::IO::DataBlockGeneric'],['../class_a_q_n_w_b_1_1_i_o_1_1_data_block_generic.html#a31df41e9b1baef44539e2f7ffda6563c',1,'AQNWB::IO::DataBlockGeneric::DataBlockGeneric()=default'],['../class_a_q_n_w_b_1_1_i_o_1_1_data_block_generic.html#aa2762cbe3631fc0318e81904d4b64ca8',1,'AQNWB::IO::DataBlockGeneric::DataBlockGeneric(const std::any &amp;inData, const std::vector&lt; SizeType &gt; &amp;inShape, const std::type_index &amp;inTypeIndex)']]],
  ['datablockgeneric_20and_20datablock_15',['DataBlockGeneric and DataBlock',['../read_page.html#read_design_data_block',1,'']]],
  ['dataset_16',['Dataset',['../class_a_q_n_w_b_1_1_types.html#a778ba605df5dabb117ede12e41111915aa49936f5ff8023036d74e6d9a599c2fa',1,'AQNWB::Types']]],
  ['datasetfield_17',['DatasetField',['../namespace_a_q_n_w_b_1_1_n_w_b.html#acfd896b65a7f56c25b3730a6e8dc80ca',1,'AQNWB::NWB']]],
  ['datasets_20and_20add_20to_20recordingcontainers_18',['4. Create datasets and add to RecordingContainers.',['../workflow.html#create_datasets',1,'']]],
  ['datasets_20and_20attributes_19',['Reading Datasets and Attributes',['../read_page.html#read_design_example_read_during',1,'']]],
  ['datasets_20and_20attributes_20',['Reading datasets and attributes',['../read_page.html#read_design_sec_read_date',1,'']]],
  ['default_5farray_5fsize_21',['DEFAULT_ARRAY_SIZE',['../_base_i_o_8hpp.html#a72040e80321fca59f8af8edf32c9ad57',1,'BaseIO.hpp']]],
  ['default_5fstr_5fsize_22',['DEFAULT_STR_SIZE',['../_base_i_o_8hpp.html#a98f9e6ca8dbaf3bf410795182a432f98',1,'BaseIO.hpp']]],
  ['define_5ffield_23',['DEFINE_FIELD',['../_registered_type_8hpp.html#acd3c876a1c357333cd4a8ff27300ee08',1,'RegisteredType.hpp']]],
  ['define_5ffield_20macro_24',['How to use the DEFINE_FIELD macro',['../registered_type_page.html#use_the_define_field_macro',1,'']]],
  ['define_5fregistered_5ffield_25',['DEFINE_REGISTERED_FIELD',['../_registered_type_8hpp.html#af374245a4f6d5a00540e9fdba52a652a',1,'RegisteredType.hpp']]],
  ['define_5fregistered_5ffield_20macro_26',['How to use the DEFINE_REGISTERED_FIELD macro',['../registered_type_page.html#use_the_define_registered_field_macro',1,'']]],
  ['design_27',['Software Design',['../read_page.html#read_design_sec',1,'']]],
  ['developer_20build_28',['Developer Build',['../dev_install_page.html#devbuild_sec',1,'']]],
  ['developer_20mode_20targets_29',['Developer Mode Targets',['../dev_install_page.html#devbuild_dev_mode_targets_subsec',1,'']]],
  ['developer_20presets_30',['Developer Presets',['../dev_install_page.html#devbuild_presets_subsec',1,'']]],
  ['developers_31',['For Developers',['../devdocs.html',1,'']]],
  ['device_32',['Device',['../class_a_q_n_w_b_1_1_n_w_b_1_1_device.html',1,'AQNWB::NWB::Device'],['../class_a_q_n_w_b_1_1_n_w_b_1_1_device.html#a2ad7fb2e8436a7accfce35978d962b74',1,'AQNWB::NWB::Device::Device()']]],
  ['device_2ecpp_33',['Device.cpp',['../_device_8cpp.html',1,'']]],
  ['device_2ehpp_34',['Device.hpp',['../_device_8hpp.html',1,'']]],
  ['dimensional_20data_35',['Using Boost Multi Array for N-Dimensional Data',['../read_page.html#read_design_data_block_multiarray',1,'']]],
  ['dimensional_20data_20as_20boost_20multi_20array_36',['Accessing multi-dimensional data as Boost multi-array',['../read_page.html#read_design_example_boostarray',1,'']]],
  ['disabled_37',['Workflow with SWMR disabled',['../hdf5io.html#hdf5io_noswmr_examples_without_swmr',1,'']]],
  ['docs_38',['Building the Docs',['../dev_docs_page.html#dev_docs_requirements_sec',1,'']]],
  ['documentation_39',['Documentation',['../dev_docs_page.html',1,'Documentation'],['../index.html#mainpage_navigation',1,'Navigating the Documentation']]],
  ['documentation_20pages_40',['Creating New Documentation Pages',['../dev_docs_page.html#dev_docs_creating',1,'']]],
  ['documentation_2edox_41',['documentation.dox',['../documentation_8dox.html',1,'']]],
  ['does_20aqnwb_20use_20smwr_20mode_42',['Why does AqNWB use SMWR mode?',['../hdf5io.html#hdf5io_swmr_features',1,'']]],
  ['dot_20graphs_43',['Creating Custom Dot Graphs',['../dev_docs_page.html#dev_docs_graphviz_sec',1,'']]],
  ['doxygen_44',['Including Code Examples in Doxygen',['../dev_docs_page.html#dev_docs_codeexamples_incl_sec',1,'']]],
  ['dstr_45',['DSTR',['../class_a_q_n_w_b_1_1_i_o_1_1_base_data_type.html#a37e661b183da280b0733e6db9fc703b1',1,'AQNWB::IO::BaseDataType']]],
  ['dynamictable_46',['DynamicTable',['../class_a_q_n_w_b_1_1_n_w_b_1_1_dynamic_table.html',1,'AQNWB::NWB::DynamicTable'],['../class_a_q_n_w_b_1_1_n_w_b_1_1_dynamic_table.html#ae46dd68e349804a320408fc289048a10',1,'AQNWB::NWB::DynamicTable::DynamicTable()']]],
  ['dynamictable_2ecpp_47',['DynamicTable.cpp',['../_dynamic_table_8cpp.html',1,'']]],
  ['dynamictable_2ehpp_48',['DynamicTable.hpp',['../_dynamic_table_8hpp.html',1,'']]]
];
