var searchData=
[
  ['a_20base_20class_20and_20templated_20child_20class_0',['Using a base class and templated child class',['../registered_type_page.html#implement_templated_registered_type_two_class',1,'']]],
  ['a_20coded_20column_1',['Setup: create the EventsTable with a coded column',['../events.html#events_meanings_setup',1,'']]],
  ['a_20custom_20hdf5_20installation_2',['Using a custom HDF5 installation',['../dev_install_page.html#devbuild_custom_hdf5_sec',1,'']]],
  ['a_20custom_20type_20name_3',['How to implement a RegisteredType with a custom type name',['../registered_type_page.html#using_registered_subclass_with_typename',1,'']]],
  ['a_20file_20from_20s3_4',['Opening a file from S3',['../reads3_page.html#reads3_ros3_open',1,'']]],
  ['a_20meaningstable_5',['Annotating columns with a MeaningsTable',['../events.html#events_meanings',1,'']]],
  ['a_20namespace_6',['Registering a Namespace',['../integrating_extensions_page.html#register_namespace',1,'']]],
  ['a_20new_20namespace_7',['How to Integrate a New Namespace',['../integrating_extensions_page.html#integrate_namespace',1,'']]],
  ['a_20new_20type_8',['Example: Implementing a New Type',['../registered_type_page.html#implement_registered_type_example',1,'']]],
  ['a_20newer_20c_20standard_20version_9',['Selecting a newer C++ standard version',['../dev_install_page.html#devbuild_cpp_std_sec',1,'']]],
  ['a_20processingmodule_10',['3. Create a ProcessingModule',['../links.html#link_processing',1,'']]],
  ['a_20recording_20workflow_11',['Overview of a recording workflow',['../workflow.html#recording_workflow',1,'']]],
  ['a_20registered_20type_20🔧_12',['Implementing a Registered Type 🔧',['../registered_type_page.html',1,'devdocs']]],
  ['a_20registeredtype_13',['How to Implement a RegisteredType',['../registered_type_page.html#implement_registered_type',1,'']]],
  ['a_20registeredtype_20with_20a_20custom_20type_20name_14',['How to implement a RegisteredType with a custom type name',['../registered_type_page.html#using_registered_subclass_with_typename',1,'']]],
  ['a_20release_15',['Making a Release',['../release_workflow.html',1,'devdocs']]],
  ['a_20release_20branch_16',['1. Create a Release Branch',['../release_workflow.html#release_steps_1',1,'']]],
  ['a_20single_20templated_20class_17',['Using a single templated class',['../registered_type_page.html#implement_templated_registered_type_single_class',1,'']]],
  ['acquiring_20data_20📊_18',['Acquiring Data 📊',['../workflow.html',1,'userdocs']]],
  ['acquiring_20event_20data_20📋_19',['Acquiring Event Data 📋',['../events.html',1,'userdocs']]],
  ['acquisition_20',['acquisition',['../events.html#events_rowbased',1,'Pattern 1: Row-based acquisition'],['../time_intervals.html#time_intervals_rowbased',1,'Pattern 1: Row-based acquisition'],['../events.html#events_colbased',1,'Pattern 2: Column-based (bulk) acquisition'],['../time_intervals.html#time_intervals_colbased',1,'Pattern 2: Column-based (bulk) acquisition']]],
  ['acquisition_5fpath_21',['ACQUISITION_PATH',['../class_a_q_n_w_b_1_1_n_w_b_1_1_n_w_b_file.html#a4664bafaa5a5b51370102b751e385768',1,'AQNWB::NWB::NWBFile']]],
  ['add_20data_20to_20columns_22',['Add data to columns',['../events.html#events_colbased_adddata',1,'Add data to columns'],['../time_intervals.html#time_intervals_colbased_adddata',1,'Add data to columns']]],
  ['add_20rows_23',['Add rows',['../events.html#events_rowbased_addrow',1,'Add rows'],['../time_intervals.html#time_intervals_rowbased_addrow',1,'Add rows']]],
  ['add_20to_20recordingobjects_24',['4. Create datasets and add to RecordingObjects',['../workflow.html#create_datasets',1,'']]],
  ['addcolumn_25',['addColumn',['../class_a_q_n_w_b_1_1_n_w_b_1_1_dynamic_table.html#abe6a2507abfb6ec7897c57aebf3318fb',1,'AQNWB::NWB::DynamicTable::addColumn(const std::shared_ptr&lt; VectorData &gt; &amp;vectorData, const std::vector&lt; std::string &gt; &amp;values)'],['../class_a_q_n_w_b_1_1_n_w_b_1_1_dynamic_table.html#af6bee79f772707a66de379c6f207e971',1,'AQNWB::NWB::DynamicTable::addColumn(const DataSpecPtr &amp;dataSpec)'],['../class_a_q_n_w_b_1_1_n_w_b_1_1_dynamic_table.html#a39b5e98d5ab26cce0658b1c11b7b7122',1,'AQNWB::NWB::DynamicTable::addColumn(const std::shared_ptr&lt; VectorData &gt; &amp;vectorData)']]],
  ['addcolumnname_26',['addColumnName',['../class_a_q_n_w_b_1_1_n_w_b_1_1_dynamic_table.html#a29dd5ff05905b47f45379e01b79aa722',1,'AQNWB::NWB::DynamicTable']]],
  ['addelectrodes_27',['addElectrodes',['../class_a_q_n_w_b_1_1_n_w_b_1_1_electrodes_table.html#ad29195cacd9a6c40fb8de417318c9cef',1,'AQNWB::NWB::ElectrodesTable']]],
  ['addfilter_28',['addFilter',['../class_a_q_n_w_b_1_1_i_o_1_1_h_d_f5_1_1_h_d_f5_array_data_set_config.html#a9aefd3b9c5e9fd7efcdb2950e63e557b',1,'AQNWB::IO::HDF5::HDF5ArrayDataSetConfig::addFilter(H5Z_filter_t filter_id, const std::vector&lt; unsigned int &gt; &amp;cd_values)'],['../class_a_q_n_w_b_1_1_i_o_1_1_h_d_f5_1_1_h_d_f5_array_data_set_config.html#af7a55a42c9cab51fe6a59abc5dfed5ef',1,'AQNWB::IO::HDF5::HDF5ArrayDataSetConfig::addFilter(const HDF5FilterConfig &amp;filter)']]],
  ['addfilters_29',['addFilters',['../class_a_q_n_w_b_1_1_i_o_1_1_h_d_f5_1_1_h_d_f5_array_data_set_config.html#accb494cb492b3a33526ab81f3a578320',1,'AQNWB::IO::HDF5::HDF5ArrayDataSetConfig']]],
  ['addrecordingobject_30',['addRecordingObject',['../class_a_q_n_w_b_1_1_i_o_1_1_recording_objects.html#a01b77fd8404c44b40b98380c600bf996',1,'AQNWB::IO::RecordingObjects']]],
  ['addreferencecolumn_31',['addReferenceColumn',['../class_a_q_n_w_b_1_1_n_w_b_1_1_dynamic_table.html#ab5d214fb6eb95bcaf0f4988b12e2b2db',1,'AQNWB::NWB::DynamicTable']]],
  ['addrow_32',['addRow',['../class_a_q_n_w_b_1_1_n_w_b_1_1_dynamic_table.html#a7fb6730f68879bbba07b968cdecac4ba',1,'AQNWB::NWB::DynamicTable']]],
  ['addrows_33',['addRows',['../class_a_q_n_w_b_1_1_n_w_b_1_1_dynamic_table.html#a2541ab21f542dfd45cfbcfe50314afd6',1,'AQNWB::NWB::DynamicTable']]],
  ['advanced_3a_20recording_20individual_20datasets_34',['Advanced: Recording individual datasets',['../workflow.html#advanced_recording_workflow',1,'']]],
  ['after_20pr_20merge_35',['6. Tag the Release (after PR merge)',['../release_workflow.html#release_steps_6',1,'']]],
  ['age_36',['age',['../struct_a_q_n_w_b_1_1_n_w_b_1_1_subject_1_1_subject_spec.html#aa8fe0236ed3c9915cc83ce13a4a4fed6',1,'AQNWB::NWB::Subject::SubjectSpec']]],
  ['agereference_37',['ageReference',['../struct_a_q_n_w_b_1_1_n_w_b_1_1_subject_1_1_subject_spec.html#a8f0b93769a2ad536d44f0f6d2f997570',1,'AQNWB::NWB::Subject::SubjectSpec']]],
  ['aligned_20timeseries_38',['Use Case: Time-Aligned TimeSeries',['../links.html#link_use_case',1,'']]],
  ['all_20channels_20at_20once_20interleaved_20data_39',['Writing all channels at once (interleaved data)',['../workflow.html#write_data_allchannels',1,'']]],
  ['all_20neurodata_5ftypes_40',['Step 3: Create RegisteredType Classes for all neurodata_types',['../integrating_extensions_page.html#labmetadata_extension_registered_type',1,'']]],
  ['an_20existing_20file_20for_20reading_41',['Opening an existing file for reading',['../read_page.html#read_example_open',1,'']]],
  ['an_20nwb_20file_20with_20swmr_20mode_42',['Writing an NWB file with SWMR mode',['../hdf5io.html#hdf5io_swmr_workflow',1,'']]],
  ['analysis_20cppcheck_43',['Static Analysis (Cppcheck)',['../testing.html#testing_cppcheck',1,'']]],
  ['analysis_5fpath_44',['ANALYSIS_PATH',['../class_a_q_n_w_b_1_1_n_w_b_1_1_n_w_b_file.html#aef1958f6da3a2dcf9ed1081d5f082398',1,'AQNWB::NWB::NWBFile']]],
  ['and_20add_20to_20recordingobjects_45',['4. Create datasets and add to RecordingObjects',['../workflow.html#create_datasets',1,'']]],
  ['and_20attributes_46',['Reading datasets and attributes',['../read_design_page.html#read_design_sec_read_date',1,'']]],
  ['and_20best_20practices_47',['Tips and best practices',['../events.html#events_tips',1,'']]],
  ['and_20compression_48',['I/O Filters and Compression',['../hdf5io.html#hdf5io_filters',1,'']]],
  ['and_20create_20the_20eventstable_49',['3. Configure and create the EventsTable',['../events.html#events_configure_table',1,'']]],
  ['and_20create_20the_20timeintervals_20table_50',['3. Configure and create the TimeIntervals table',['../time_intervals.html#time_intervals_configure_table',1,'']]],
  ['and_20data_51',['Reading objects and data',['../reads3_page.html#reads3_ros3_read',1,'']]],
  ['and_20finalize_20the_20file_52',['7. Stop the recording and finalize the file',['../workflow.html#stop_recording',1,'']]],
  ['and_20i_20o_20filters_20in_20aqnwb_53',['Using Chunking and I/O Filters in AqNWB',['../hdf5io.html#hdf5io_filters_usage',1,'']]],
  ['and_20memory_20management_54',['Object and memory management',['../record_design_page.html#record_design_object_memory_management',1,'']]],
  ['and_20processing_20data_55',['Reading and Processing Data',['../read_design_page.html#read_design_example_read',1,'']]],
  ['and_20push_20changes_56',['3. Commit and Push Changes',['../release_workflow.html#release_steps_3',1,'']]],
  ['and_20table_20creation_57',['and table creation',['../events.html#events_setup',1,'Setup: I/O, NWBFile, and table creation'],['../time_intervals.html#time_intervals_setup',1,'Setup: I/O, NWBFile, and table creation']]],
  ['and_20templated_20child_20class_58',['Using a base class and templated child class',['../registered_type_page.html#implement_templated_registered_type_two_class',1,'']]],
  ['and_20test_59',['Configure, Build and Test',['../dev_install_page.html#configure_build_test',1,'']]],
  ['and_20write_20methods_20for_20datasets_60',['DEFINE_DATASET_FIELD: Creating read and write methods for datasets',['../registered_type_page.html#use_the_define_dataset_field_macro',1,'']]],
  ['and_20writing_20data_61',['Creating and Writing Data',['../read_design_page.html#read_design_example_create',1,'']]],
  ['annotating_20columns_20with_20a_20meaningstable_62',['Annotating columns with a MeaningsTable',['../events.html#events_meanings',1,'']]],
  ['annotating_20time_20intervals_20⏱️_63',['Annotating Time Intervals ⏱️',['../time_intervals.html',1,'userdocs']]],
  ['annotationseries_64',['AnnotationSeries',['../class_a_q_n_w_b_1_1_n_w_b_1_1_annotation_series.html',1,'AQNWB::NWB::AnnotationSeries'],['../class_a_q_n_w_b_1_1_n_w_b_1_1_annotation_series.html#ab98f231850a75a82fade2234e8606359',1,'AQNWB::NWB::AnnotationSeries::AnnotationSeries()']]],
  ['annotationseries_2ecpp_65',['AnnotationSeries.cpp',['../_annotation_series_8cpp.html',1,'']]],
  ['annotationseries_2ehpp_66',['AnnotationSeries.hpp',['../_annotation_series_8hpp.html',1,'']]],
  ['appendbuffer_67',['appendBuffer',['../class_a_q_n_w_b_1_1_n_w_b_1_1_vector_data.html#a0fe5c2f70e1922244ea702db4fec8f6f',1,'AQNWB::NWB::VectorData']]],
  ['appendcellvaluetobuffer_68',['appendCellValueToBuffer',['../namespace_a_q_n_w_b.html#ab61fb380a62609e576ed5fe352b3e94f',1,'AQNWB']]],
  ['appenddata_69',['appendData',['../class_a_q_n_w_b_1_1_n_w_b_1_1_vector_data.html#a5d5d48aef5b2b049c5ca1b16e15c63c8',1,'AQNWB::NWB::VectorData::appendData()'],['../class_a_q_n_w_b_1_1_n_w_b_1_1_vector_index.html#a63166d71772ab8ca8de54141bfc314dc',1,'AQNWB::NWB::VectorIndex::appendData()']]],
  ['aqnwb_70',['AQNWB',['../namespace_a_q_n_w_b.html',1,'']]],
  ['aqnwb_71',['AqNWB',['../user_demos.html#demos_inspect_electrical_series',1,'Inspect Electrical Series Data using AqNWB'],['../dev_install_page.html#dev_install_aqnwb_sec',1,'Installing AqNWB'],['../user_demos.html#demos_labmetadata_extension',1,'Integrating LabMetaData Extension with AqNWB'],['../hdf5io.html#hdf5io_filters_usage',1,'Using Chunking and I/O Filters in AqNWB']]],
  ['aqnwb_20use_20smwr_20mode_72',['Why does AqNWB use SMWR mode?',['../hdf5io.html#hdf5io_swmr_features',1,'']]],
  ['aqnwb_3a_3adetail_73',['detail',['../namespace_a_q_n_w_b_1_1detail.html',1,'AQNWB']]],
  ['aqnwb_3a_3aio_74',['IO',['../namespace_a_q_n_w_b_1_1_i_o.html',1,'AQNWB']]],
  ['aqnwb_3a_3aio_3a_3ahdf5_75',['HDF5',['../namespace_a_q_n_w_b_1_1_i_o_1_1_h_d_f5.html',1,'AQNWB::IO']]],
  ['aqnwb_3a_3anwb_76',['NWB',['../namespace_a_q_n_w_b_1_1_n_w_b.html',1,'AQNWB']]],
  ['aqnwb_3a_3anwb_3a_3aregisteredtype_77',['AQNWB::NWB::RegisteredType',['../class_a_q_n_w_b_1_1_n_w_b_1_1_data_typed.html#a592540e985a1aa371bf785d992d2785a',1,'AQNWB::NWB::DataTyped::RegisteredType()'],['../class_a_q_n_w_b_1_1_n_w_b_1_1_vector_data_typed.html#a592540e985a1aa371bf785d992d2785a',1,'AQNWB::NWB::VectorDataTyped::RegisteredType()']]],
  ['aqnwb_3a_3aspec_78',['SPEC',['../namespace_a_q_n_w_b_1_1_s_p_e_c.html',1,'AQNWB']]],
  ['aqnwb_3a_3aspec_3a_3acore_79',['CORE',['../namespace_a_q_n_w_b_1_1_s_p_e_c_1_1_c_o_r_e.html',1,'AQNWB::SPEC']]],
  ['aqnwb_3a_3aspec_3a_3ahdmf_5fcommon_80',['HDMF_COMMON',['../namespace_a_q_n_w_b_1_1_s_p_e_c_1_1_h_d_m_f___c_o_m_m_o_n.html',1,'AQNWB::SPEC']]],
  ['aqnwb_3a_3aspec_3a_3ahdmf_5fexperimental_81',['HDMF_EXPERIMENTAL',['../namespace_a_q_n_w_b_1_1_s_p_e_c_1_1_h_d_m_f___e_x_p_e_r_i_m_e_n_t_a_l.html',1,'AQNWB::SPEC']]],
  ['aqnwb_3a_3atypes_82',['Types',['../namespace_a_q_n_w_b_1_1_types.html',1,'AQNWB']]],
  ['arbitrary_20fields_83',['Reading arbitrary fields',['../read_page.html#read_example_arbitrary',1,'']]],
  ['arraydatasetconfig_84',['ArrayDataSetConfig',['../class_a_q_n_w_b_1_1_i_o_1_1_array_data_set_config.html',1,'AQNWB::IO::ArrayDataSetConfig'],['../class_a_q_n_w_b_1_1_i_o_1_1_array_data_set_config.html#abe5aa8c2e9f5d7ad2a0ca4da2d7d5fd9',1,'AQNWB::IO::ArrayDataSetConfig::ArrayDataSetConfig()']]],
  ['as_5fmulti_5farray_85',['as_multi_array',['../class_a_q_n_w_b_1_1_i_o_1_1_data_block.html#aaf2d60165126bf43841cfe17361d7912',1,'AQNWB::IO::DataBlock']]],
  ['as_5fvariant_86',['as_variant',['../class_a_q_n_w_b_1_1_i_o_1_1_data_block_generic.html#a957ab6f55f6be707def1ae317948a6eb',1,'AQNWB::IO::DataBlockGeneric']]],
  ['at_20once_20interleaved_20data_87',['Writing all channels at once (interleaved data)',['../workflow.html#write_data_allchannels',1,'']]],
  ['attribute_88',['Attribute',['../namespace_a_q_n_w_b_1_1_types.html#a778ba605df5dabb117ede12e41111915a459ad320d6c923a4111734767c71b20c',1,'AQNWB::Types']]],
  ['attributeexists_89',['attributeExists',['../class_a_q_n_w_b_1_1_i_o_1_1_base_i_o.html#a06b5edf2bbd4c85adcafda13e7903873',1,'AQNWB::IO::BaseIO::attributeExists()'],['../class_a_q_n_w_b_1_1_i_o_1_1_h_d_f5_1_1_h_d_f5_i_o.html#a53bfbbdbf24afdd97ea45294b65c1e37',1,'AQNWB::IO::HDF5::HDF5IO::attributeExists()']]],
  ['attributefield_90',['AttributeField',['../namespace_a_q_n_w_b_1_1_n_w_b.html#a4a7413b10eb1a838f0349fc59b5a333f',1,'AQNWB::NWB']]],
  ['attributes_91',['attributes',['../registered_type_page.html#use_the_define_attribute_field_macro',1,'DEFINE_ATTRIBUTE_FIELD: Creating read methods for attributes'],['../read_design_page.html#read_design_sec_read_date',1,'Reading datasets and attributes']]],
  ['automated_20tests_20on_20github_92',['Automated tests on GitHub',['../testing.html#testing_github',1,'']]]
];
