var searchData=
[
  ['e_20g_20container_0',['Child classes of RegisteredType (e.g., Container)',['../read_page.html#read_design_wrapper_subtypes',1,'']]],
  ['e_20g_20electricalseries_1',['Searching for Registered Type objects (e.g.,ElectricalSeries)',['../read_page.html#read_design_example_read_posthoc_search',1,'']]],
  ['electricalseries_2',['ElectricalSeries',['../class_a_q_n_w_b_1_1_n_w_b_1_1_electrical_series.html',1,'AQNWB::NWB::ElectricalSeries'],['../class_a_q_n_w_b_1_1_n_w_b_1_1_electrical_series.html#a684a7b01cb955d7335f07d5eaab2250b',1,'AQNWB::NWB::ElectricalSeries::ElectricalSeries()'],['../read_page.html#read_design_example_read_posthoc_search',1,'Searching for Registered Type objects (e.g.,ElectricalSeries)']]],
  ['electricalseries_2ecpp_3',['ElectricalSeries.cpp',['../_electrical_series_8cpp.html',1,'']]],
  ['electricalseries_2ehpp_4',['ElectricalSeries.hpp',['../_electrical_series_8hpp.html',1,'']]],
  ['electrodegroup_5',['ElectrodeGroup',['../class_a_q_n_w_b_1_1_n_w_b_1_1_electrode_group.html',1,'AQNWB::NWB::ElectrodeGroup'],['../class_a_q_n_w_b_1_1_n_w_b_1_1_electrode_group.html#a7cfae9f37d17f90486921d0b6445a9cd',1,'AQNWB::NWB::ElectrodeGroup::ElectrodeGroup()']]],
  ['electrodegroup_2ecpp_6',['ElectrodeGroup.cpp',['../_electrode_group_8cpp.html',1,'']]],
  ['electrodegroup_2ehpp_7',['ElectrodeGroup.hpp',['../_electrode_group_8hpp.html',1,'']]],
  ['electrodetable_8',['ElectrodeTable',['../class_a_q_n_w_b_1_1_n_w_b_1_1_electrode_table.html',1,'AQNWB::NWB::ElectrodeTable'],['../class_a_q_n_w_b_1_1_n_w_b_1_1_electrode_table.html#a0d66d1ec3b341bb3132be86279d9f4c6',1,'AQNWB::NWB::ElectrodeTable::ElectrodeTable(std::shared_ptr&lt; IO::BaseIO &gt; io)'],['../class_a_q_n_w_b_1_1_n_w_b_1_1_electrode_table.html#ab1c5db466e0cb350012b03253dff424a',1,'AQNWB::NWB::ElectrodeTable::ElectrodeTable(const std::string &amp;path, std::shared_ptr&lt; IO::BaseIO &gt; io)']]],
  ['electrodetable_2ecpp_9',['ElectrodeTable.cpp',['../_electrode_table_8cpp.html',1,'']]],
  ['electrodetable_2ehpp_10',['ElectrodeTable.hpp',['../_electrode_table_8hpp.html',1,'']]],
  ['electrodetablepath_11',['electrodeTablePath',['../class_a_q_n_w_b_1_1_n_w_b_1_1_electrode_table.html#a2375dcafcd8ab00dd313d3fec121fa42',1,'AQNWB::NWB::ElectrodeTable']]],
  ['elementidentifiers_12',['ElementIdentifiers',['../class_a_q_n_w_b_1_1_n_w_b_1_1_element_identifiers.html',1,'AQNWB::NWB::ElementIdentifiers'],['../class_a_q_n_w_b_1_1_n_w_b_1_1_element_identifiers.html#a40f8d890a3fd976858bedc91e08fd745',1,'AQNWB::NWB::ElementIdentifiers::ElementIdentifiers()']]],
  ['elementidentifiers_2ecpp_13',['ElementIdentifiers.cpp',['../_element_identifiers_8cpp.html',1,'']]],
  ['elementidentifiers_2ehpp_14',['ElementIdentifiers.hpp',['../_element_identifiers_8hpp.html',1,'']]],
  ['emptycontainerindexes_15',['emptyContainerIndexes',['../class_a_q_n_w_b_1_1_n_w_b_1_1_n_w_b_file.html#ab90425a28d3d4108def9aa5b4386a262',1,'AQNWB::NWB::NWBFile']]],
  ['example_16',['Example',['../read_page.html#read_design_example',1,'']]],
  ['example_20code_17',['Example Code',['../dev_docs_page.html#dev_docs_codeexamples_def_sec',1,'Creating the Example Code'],['../dev_docs_page.html#dev_docs_codeexamples_run_sec',1,'Testing the Example Code']]],
  ['example_3a_20implementing_20a_20new_20type_18',['Example: Implementing a new type',['../registered_type_page.html#implement_registered_type_example',1,'']]],
  ['example_3a_20using_20the_20type_20registry_19',['Example: Using the type registry',['../registered_type_page.html#use_registered_type_registry_example',1,'']]],
  ['examples_20',['Examples',['../hdf5io.html#hdf5io_swmr_examples',1,'Code Examples'],['../dev_docs_page.html#dev_docs_codeexamples_sec',1,'Creating Code Examples']]],
  ['examples_20in_20doxygen_21',['Including Code Examples in Doxygen',['../dev_docs_page.html#dev_docs_codeexamples_incl_sec',1,'']]],
  ['existing_20file_22',['Reading from an existing file',['../read_page.html#read_design_example_read_from_existing_file',1,'']]],
  ['existing_20file_20for_20reading_23',['Opening an existing file for reading',['../read_page.html#read_design_example_read_create_io',1,'']]],
  ['exists_24',['exists',['../read_page.html#read_design_example_check_exists',1,'Check that the object exists'],['../class_a_q_n_w_b_1_1_i_o_1_1_read_data_wrapper.html#aa67d145711df12192d43d07c3a52546a',1,'AQNWB::IO::ReadDataWrapper::exists()']]],
  ['experimental_25',['experimental',['../namespace_a_q_n_w_b_1_1_s_p_e_c_1_1_h_d_m_f___e_x_p_e_r_i_m_e_n_t_a_l.html#ac353ef164be0c431a75ad8f7a36129ca',1,'AQNWB::SPEC::HDMF_EXPERIMENTAL']]]
];
