var searchData=
[
  ['a_20base_20class_20and_20templated_20child_20class_0',['Using a base class and templated child class',['../registered_type_page.html#implement_templated_registered_type_two_class',1,'']]],
  ['a_20custom_20type_20name_1',['How to implement a RegisteredType with a custom type name',['../registered_type_page.html#using_registered_subclass_with_typename',1,'']]],
  ['a_20namespace_2',['Registering a Namespace',['../integrating_extensions_page.html#register_namespace',1,'']]],
  ['a_20new_20namespace_3',['How to Integrate a New Namespace',['../integrating_extensions_page.html#integrate_namespace',1,'']]],
  ['a_20new_20type_4',['Example: Implementing a New Type',['../registered_type_page.html#implement_registered_type_example',1,'']]],
  ['a_20recording_20workflow_5',['Overview of a recording workflow',['../workflow.html#recording_workflow',1,'']]],
  ['a_20registered_20type_20🔧_6',['Implementing a Registered Type 🔧',['../registered_type_page.html',1,'devdocs']]],
  ['a_20registeredtype_7',['How to Implement a RegisteredType',['../registered_type_page.html#implement_registered_type',1,'']]],
  ['a_20registeredtype_20with_20a_20custom_20type_20name_8',['How to implement a RegisteredType with a custom type name',['../registered_type_page.html#using_registered_subclass_with_typename',1,'']]],
  ['a_20single_20templated_20class_9',['Using a single templated class',['../registered_type_page.html#implement_templated_registered_type_single_class',1,'']]],
  ['acquiring_20data_20📊_10',['Acquiring Data 📊',['../workflow.html',1,'userdocs']]],
  ['add_20to_20recordingcontainers_11',['5. Create datasets and add to RecordingContainers.',['../workflow.html#create_datasets',1,'']]],
  ['addcolumn_12',['addColumn',['../class_a_q_n_w_b_1_1_n_w_b_1_1_dynamic_table.html#a916169b9c8b324833861df2af1b59c3f',1,'AQNWB::NWB::DynamicTable']]],
  ['addcontainer_13',['addContainer',['../class_a_q_n_w_b_1_1_n_w_b_1_1_recording_containers.html#a446ec0d5f5e7802d9e44725399c71e8c',1,'AQNWB::NWB::RecordingContainers']]],
  ['addelectrodes_14',['addElectrodes',['../class_a_q_n_w_b_1_1_n_w_b_1_1_electrode_table.html#a41f29ce1a76fd932eac4a03e67d8268f',1,'AQNWB::NWB::ElectrodeTable']]],
  ['addfilter_15',['addFilter',['../class_a_q_n_w_b_1_1_i_o_1_1_h_d_f5_1_1_h_d_f5_array_data_set_config.html#a9aefd3b9c5e9fd7efcdb2950e63e557b',1,'AQNWB::IO::HDF5::HDF5ArrayDataSetConfig::addFilter(H5Z_filter_t filter_id, const std::vector&lt; unsigned int &gt; &amp;cd_values)'],['../class_a_q_n_w_b_1_1_i_o_1_1_h_d_f5_1_1_h_d_f5_array_data_set_config.html#af7a55a42c9cab51fe6a59abc5dfed5ef',1,'AQNWB::IO::HDF5::HDF5ArrayDataSetConfig::addFilter(const HDF5FilterConfig &amp;filter)']]],
  ['addfilters_16',['addFilters',['../class_a_q_n_w_b_1_1_i_o_1_1_h_d_f5_1_1_h_d_f5_array_data_set_config.html#accb494cb492b3a33526ab81f3a578320',1,'AQNWB::IO::HDF5::HDF5ArrayDataSetConfig']]],
  ['addreferencecolumn_17',['addReferenceColumn',['../class_a_q_n_w_b_1_1_n_w_b_1_1_dynamic_table.html#ab5d214fb6eb95bcaf0f4988b12e2b2db',1,'AQNWB::NWB::DynamicTable']]],
  ['all_20neurodata_5ftypes_18',['Step 3: Create RegisteredType Classes for all neurodata_types',['../integrating_extensions_page.html#labmetadata_extension_registered_type',1,'']]],
  ['an_20existing_20file_20for_20reading_19',['Opening an existing file for reading',['../read_page.html#read_example_open',1,'']]],
  ['an_20nwb_20file_20with_20swmr_20mode_20',['Writing an NWB file with SWMR mode',['../hdf5io.html#hdf5io_swmr_workflow',1,'']]],
  ['and_20add_20to_20recordingcontainers_21',['5. Create datasets and add to RecordingContainers.',['../workflow.html#create_datasets',1,'']]],
  ['and_20attributes_22',['and attributes',['../registered_type_page.html#use_the_define_field_macro',1,'DEFINE_FIELD: Creating read methods for datasets and attributes'],['../read_design_page.html#read_design_sec_read_date',1,'Reading datasets and attributes']]],
  ['and_20compression_23',['I/O Filters and Compression',['../hdf5io.html#hdf5io_filters',1,'']]],
  ['and_20finalize_20the_20file_24',['8. Stop the recording and finalize the file.',['../workflow.html#stop_recording',1,'']]],
  ['and_20i_20o_20filters_20in_20aqnwb_25',['Using Chunking and I/O Filters in AqNWB',['../hdf5io.html#hdf5io_filters_usage',1,'']]],
  ['and_20processing_20data_26',['Reading and Processing Data',['../read_design_page.html#read_design_example_read',1,'']]],
  ['and_20templated_20child_20class_27',['Using a base class and templated child class',['../registered_type_page.html#implement_templated_registered_type_two_class',1,'']]],
  ['and_20test_28',['Configure, Build and Test',['../dev_install_page.html#configure_build_test',1,'']]],
  ['and_20writing_20data_29',['Creating and Writing Data',['../read_design_page.html#read_design_example_create',1,'']]],
  ['annotationseries_30',['AnnotationSeries',['../class_a_q_n_w_b_1_1_n_w_b_1_1_annotation_series.html',1,'AQNWB::NWB::AnnotationSeries'],['../class_a_q_n_w_b_1_1_n_w_b_1_1_annotation_series.html#ab98f231850a75a82fade2234e8606359',1,'AQNWB::NWB::AnnotationSeries::AnnotationSeries()']]],
  ['annotationseries_2ecpp_31',['AnnotationSeries.cpp',['../_annotation_series_8cpp.html',1,'']]],
  ['annotationseries_2ehpp_32',['AnnotationSeries.hpp',['../_annotation_series_8hpp.html',1,'']]],
  ['aqnwb_33',['AQNWB',['../namespace_a_q_n_w_b.html',1,'']]],
  ['aqnwb_34',['AqNWB',['../user_demos.html#demos_inspect_electrical_series',1,'Inspect Electrical Series Data using AqNWB'],['../user_demos.html#demos_labmetadata_extension',1,'Integrating LabMetaData Extension with AqNWB'],['../hdf5io.html#hdf5io_filters_usage',1,'Using Chunking and I/O Filters in AqNWB']]],
  ['aqnwb_20use_20smwr_20mode_35',['Why does AqNWB use SMWR mode?',['../hdf5io.html#hdf5io_swmr_features',1,'']]],
  ['aqnwb_3a_3aio_36',['IO',['../namespace_a_q_n_w_b_1_1_i_o.html',1,'AQNWB']]],
  ['aqnwb_3a_3aio_3a_3ahdf5_37',['HDF5',['../namespace_a_q_n_w_b_1_1_i_o_1_1_h_d_f5.html',1,'AQNWB::IO']]],
  ['aqnwb_3a_3anwb_38',['NWB',['../namespace_a_q_n_w_b_1_1_n_w_b.html',1,'AQNWB']]],
  ['aqnwb_3a_3aspec_39',['SPEC',['../namespace_a_q_n_w_b_1_1_s_p_e_c.html',1,'AQNWB']]],
  ['aqnwb_3a_3aspec_3a_3acore_40',['CORE',['../namespace_a_q_n_w_b_1_1_s_p_e_c_1_1_c_o_r_e.html',1,'AQNWB::SPEC']]],
  ['aqnwb_3a_3aspec_3a_3ahdmf_5fcommon_41',['HDMF_COMMON',['../namespace_a_q_n_w_b_1_1_s_p_e_c_1_1_h_d_m_f___c_o_m_m_o_n.html',1,'AQNWB::SPEC']]],
  ['aqnwb_3a_3aspec_3a_3ahdmf_5fexperimental_42',['HDMF_EXPERIMENTAL',['../namespace_a_q_n_w_b_1_1_s_p_e_c_1_1_h_d_m_f___e_x_p_e_r_i_m_e_n_t_a_l.html',1,'AQNWB::SPEC']]],
  ['arbitrary_20fields_43',['Reading arbitrary fields',['../read_page.html#read_example_arbitrary',1,'']]],
  ['arraydatasetconfig_44',['ArrayDataSetConfig',['../class_a_q_n_w_b_1_1_i_o_1_1_array_data_set_config.html',1,'AQNWB::IO::ArrayDataSetConfig'],['../class_a_q_n_w_b_1_1_i_o_1_1_array_data_set_config.html#abe5aa8c2e9f5d7ad2a0ca4da2d7d5fd9',1,'AQNWB::IO::ArrayDataSetConfig::ArrayDataSetConfig()']]],
  ['as_5fmulti_5farray_45',['as_multi_array',['../class_a_q_n_w_b_1_1_i_o_1_1_data_block.html#a39c4d437721b818aac335f3c9a57dc97',1,'AQNWB::IO::DataBlock']]],
  ['as_5fvariant_46',['as_variant',['../class_a_q_n_w_b_1_1_i_o_1_1_data_block_generic.html#a957ab6f55f6be707def1ae317948a6eb',1,'AQNWB::IO::DataBlockGeneric']]],
  ['attribute_47',['Attribute',['../class_a_q_n_w_b_1_1_types.html#a778ba605df5dabb117ede12e41111915a459ad320d6c923a4111734767c71b20c',1,'AQNWB::Types']]],
  ['attributeexists_48',['attributeExists',['../class_a_q_n_w_b_1_1_i_o_1_1_base_i_o.html#a06b5edf2bbd4c85adcafda13e7903873',1,'AQNWB::IO::BaseIO::attributeExists()'],['../class_a_q_n_w_b_1_1_i_o_1_1_h_d_f5_1_1_h_d_f5_i_o.html#a53bfbbdbf24afdd97ea45294b65c1e37',1,'AQNWB::IO::HDF5::HDF5IO::attributeExists()']]],
  ['attributefield_49',['AttributeField',['../namespace_a_q_n_w_b_1_1_n_w_b.html#a4a7413b10eb1a838f0349fc59b5a333f',1,'AQNWB::NWB']]],
  ['attributes_50',['attributes',['../registered_type_page.html#use_the_define_field_macro',1,'DEFINE_FIELD: Creating read methods for datasets and attributes'],['../read_design_page.html#read_design_sec_read_date',1,'Reading datasets and attributes']]],
  ['automated_20tests_20on_20github_51',['Automated tests on GitHub',['../testing.html#testing_github',1,'']]]
];
