var searchData=
[
  ['electrical_20series_20data_20using_20aqnwb_0',['Inspect Electrical Series Data using AqNWB',['../user_demos.html#demos_inspect_electrical_series',1,'']]],
  ['electricalseries_1',['ElectricalSeries',['../class_a_q_n_w_b_1_1_n_w_b_1_1_electrical_series.html',1,'AQNWB::NWB::ElectricalSeries'],['../class_a_q_n_w_b_1_1_n_w_b_1_1_electrical_series.html#a684a7b01cb955d7335f07d5eaab2250b',1,'AQNWB::NWB::ElectricalSeries::ElectricalSeries()']]],
  ['electricalseries_2ecpp_2',['ElectricalSeries.cpp',['../_electrical_series_8cpp.html',1,'']]],
  ['electricalseries_2ehpp_3',['ElectricalSeries.hpp',['../_electrical_series_8hpp.html',1,'']]],
  ['electrodegroup_4',['ElectrodeGroup',['../class_a_q_n_w_b_1_1_n_w_b_1_1_electrode_group.html',1,'AQNWB::NWB::ElectrodeGroup'],['../class_a_q_n_w_b_1_1_n_w_b_1_1_electrode_group.html#a7cfae9f37d17f90486921d0b6445a9cd',1,'AQNWB::NWB::ElectrodeGroup::ElectrodeGroup()']]],
  ['electrodegroup_2ecpp_5',['ElectrodeGroup.cpp',['../_electrode_group_8cpp.html',1,'']]],
  ['electrodegroup_2ehpp_6',['ElectrodeGroup.hpp',['../_electrode_group_8hpp.html',1,'']]],
  ['electrodestable_7',['ElectrodesTable',['../class_a_q_n_w_b_1_1_n_w_b_1_1_electrodes_table.html',1,'AQNWB::NWB::ElectrodesTable'],['../class_a_q_n_w_b_1_1_n_w_b_1_1_electrodes_table.html#ac59e22d783a27642e78472f435943c9a',1,'AQNWB::NWB::ElectrodesTable::ElectrodesTable(std::shared_ptr&lt; IO::BaseIO &gt; io)'],['../class_a_q_n_w_b_1_1_n_w_b_1_1_electrodes_table.html#a619418bc86a44930589f2cfb8326bd22',1,'AQNWB::NWB::ElectrodesTable::ElectrodesTable(const std::string &amp;path, std::shared_ptr&lt; IO::BaseIO &gt; io)']]],
  ['electrodestable_2ecpp_8',['ElectrodesTable.cpp',['../_electrodes_table_8cpp.html',1,'']]],
  ['electrodestable_2ehpp_9',['ElectrodesTable.hpp',['../_electrodes_table_8hpp.html',1,'']]],
  ['electrodestablepath_10',['electrodesTablePath',['../class_a_q_n_w_b_1_1_n_w_b_1_1_electrodes_table.html#a869b69cfe13df06d73f174e466a267fd',1,'AQNWB::NWB::ElectrodesTable']]],
  ['elementidentifiers_11',['ElementIdentifiers',['../class_a_q_n_w_b_1_1_n_w_b_1_1_element_identifiers.html',1,'AQNWB::NWB::ElementIdentifiers'],['../class_a_q_n_w_b_1_1_n_w_b_1_1_element_identifiers.html#a40f8d890a3fd976858bedc91e08fd745',1,'AQNWB::NWB::ElementIdentifiers::ElementIdentifiers()']]],
  ['elementidentifiers_2ecpp_12',['ElementIdentifiers.cpp',['../_element_identifiers_8cpp.html',1,'']]],
  ['elementidentifiers_2ehpp_13',['ElementIdentifiers.hpp',['../_element_identifiers_8hpp.html',1,'']]],
  ['end_14',['end',['../class_a_q_n_w_b_1_1_i_o_1_1_const_multi_array_view.html#a66ef0ef534752b7c3cb96d2b0f7829a5',1,'AQNWB::IO::ConstMultiArrayView']]],
  ['ensureconfiguredcolumnsloaded_15',['ensureConfiguredColumnsLoaded',['../class_a_q_n_w_b_1_1_n_w_b_1_1_dynamic_table.html#ac43e333295fe72f2d87f0e88ced5be55',1,'AQNWB::NWB::DynamicTable']]],
  ['event_20data_16',['Write event data',['../events.html#events_meanings_write_events',1,'']]],
  ['event_20data_20📋_17',['Acquiring Event Data 📋',['../events.html',1,'userdocs']]],
  ['events_2edox_18',['events.dox',['../events_8dox.html',1,'']]],
  ['events_5fpath_19',['EVENTS_PATH',['../class_a_q_n_w_b_1_1_n_w_b_1_1_n_w_b_file.html#a70cdc1fe7a82431c4f30383ffb505a00',1,'AQNWB::NWB::NWBFile']]],
  ['eventstable_20',['EventsTable',['../events.html#events_configure_table',1,'3. Configure and create the EventsTable'],['../class_a_q_n_w_b_1_1_n_w_b_1_1_events_table.html',1,'AQNWB::NWB::EventsTable'],['../class_a_q_n_w_b_1_1_n_w_b_1_1_events_table.html#afbf7155ae475c2eb7a7e8fa68957f14a',1,'AQNWB::NWB::EventsTable::EventsTable()']]],
  ['eventstable_20with_20a_20coded_20column_21',['Setup: create the EventsTable with a coded column',['../events.html#events_meanings_setup',1,'']]],
  ['eventstable_2ecpp_22',['EventsTable.cpp',['../_events_table_8cpp.html',1,'']]],
  ['eventstable_2ehpp_23',['EventsTable.hpp',['../_events_table_8hpp.html',1,'']]],
  ['example_20code_24',['Example Code',['../dev_docs_page.html#dev_docs_codeexamples_def_sec',1,'Creating the Example Code'],['../dev_docs_page.html#dev_docs_codeexamples_run_sec',1,'Testing the Example Code']]],
  ['example_20implementation_20details_25',['Example Implementation Details',['../read_design_page.html#read_design_example',1,'']]],
  ['example_3a_20implementing_20a_20new_20type_26',['Example: Implementing a New Type',['../registered_type_page.html#implement_registered_type_example',1,'']]],
  ['example_3a_20using_20the_20type_20registry_27',['Example: Using the type registry',['../read_design_page.html#use_registered_type_registry_example',1,'']]],
  ['examples_28',['Examples',['../hdf5io.html#hdf5io_swmr_examples',1,'Code Examples'],['../dev_docs_page.html#dev_docs_codeexamples_sec',1,'Creating Code Examples']]],
  ['examples_20in_20doxygen_29',['Including Code Examples in Doxygen',['../dev_docs_page.html#dev_docs_codeexamples_incl_sec',1,'']]],
  ['existing_20file_20for_20reading_30',['Opening an existing file for reading',['../read_page.html#read_example_open',1,'']]],
  ['exists_31',['exists',['../class_a_q_n_w_b_1_1_i_o_1_1_read_data_wrapper.html#aa67d145711df12192d43d07c3a52546a',1,'AQNWB::IO::ReadDataWrapper']]],
  ['experimental_32',['experimental',['../namespace_a_q_n_w_b_1_1_s_p_e_c_1_1_h_d_m_f___e_x_p_e_r_i_m_e_n_t_a_l.html#ac353ef164be0c431a75ad8f7a36129ca',1,'AQNWB::SPEC::HDMF_EXPERIMENTAL']]],
  ['extension_33',['Extension',['../integrating_extensions_page.html#labmetadata_extension_schema',1,'Step 1: Get the Schema of the Extension'],['../integrating_extensions_page.html#labmetadata_extension_usage',1,'Step 4: Using the Extension']]],
  ['extension_20demo_34',['LabMetaData Extension Demo',['../integrating_extensions_page.html#labmetadata_extension_demo',1,'']]],
  ['extension_20with_20aqnwb_35',['Integrating LabMetaData Extension with AqNWB',['../user_demos.html#demos_labmetadata_extension',1,'']]],
  ['extensions_20🧩_36',['Integrating NWB Extensions 🧩',['../integrating_extensions_page.html',1,'devdocs']]],
  ['extracellular_20recording_20metadata_37',['Create the extracellular recording metadata',['../workflow.html#create_recmeta_ecephys',1,'']]],
  ['extractindexvalue_38',['extractIndexValue',['../class_a_q_n_w_b_1_1_n_w_b_1_1_vector_index.html#a6ed59fcb591ce449a19d8aab2a5729e1',1,'AQNWB::NWB::VectorIndex']]]
];
