var searchData=
[
  ['target_20options_0',['Target options',['../dev_install_page.html#devbuild_target_options_subsubsec',1,'']]],
  ['targets_1',['Developer Mode Targets',['../dev_install_page.html#devbuild_dev_mode_targets_subsec',1,'']]],
  ['templated_20child_20class_2',['Using a base class and templated child class',['../registered_type_page.html#implement_templated_registered_type_two_class',1,'']]],
  ['templated_20class_3',['Using a single templated class',['../registered_type_page.html#implement_templated_registered_type_single_class',1,'']]],
  ['templated_20registeredtype_20classes_4',['Templated RegisteredType Classes',['../registered_type_page.html#implement_templated_registered_type',1,'']]],
  ['templated_20registeredtype_20classes_5',['Reading templated RegisteredType classes',['../read_design_page.html#read_design_templates',1,'']]],
  ['test_6',['Configure, Build and Test',['../dev_install_page.html#configure_build_test',1,'']]],
  ['testing_20🛡️_7',['Testing 🛡️',['../testing.html',1,'devdocs']]],
  ['testing_20registeredtypes_8',['Testing RegisteredTypes',['../registered_type_page.html#implement_registered_type_unit_tests',1,'']]],
  ['testing_20the_20example_20code_9',['Testing the Example Code',['../dev_docs_page.html#dev_docs_codeexamples_run_sec',1,'']]],
  ['tests_10',['Tests',['../testing.html#testing_unit_run',1,'Running Unit Tests'],['../testing.html#testing_unit',1,'Unit Tests']]],
  ['tests_20on_20github_11',['Automated tests on GitHub',['../testing.html#testing_github',1,'']]],
  ['the_20define_5fdataset_5ffield_20macro_20for_20recording_12',['The DEFINE_DATASET_FIELD Macro for Recording',['../record_design_page.html#record_design_sec_define_dataset_field',1,'']]],
  ['the_20docs_13',['Building the Docs',['../dev_docs_page.html#dev_docs_requirements_sec',1,'']]],
  ['the_20example_20code_14',['the Example Code',['../dev_docs_page.html#dev_docs_codeexamples_def_sec',1,'Creating the Example Code'],['../dev_docs_page.html#dev_docs_codeexamples_run_sec',1,'Testing the Example Code']]],
  ['the_20extension_15',['the Extension',['../integrating_extensions_page.html#labmetadata_extension_schema',1,'Step 1: Get the Schema of the Extension'],['../integrating_extensions_page.html#labmetadata_extension_usage',1,'Step 4: Using the Extension']]],
  ['the_20extracellular_20recording_20metadata_16',['Create the extracellular recording metadata',['../workflow.html#create_recmeta_ecephys',1,'']]],
  ['the_20file_17',['7. Stop the recording and finalize the file.',['../workflow.html#stop_recording',1,'']]],
  ['the_20generate_20types_20command_18',['Using the generate-types command',['../registered_type_page.html#using_schematype_to_aqnwb',1,'']]],
  ['the_20i_20o_20object_19',['1. Create the I/O object',['../workflow.html#create_io',1,'']]],
  ['the_20namespaceregistry_20works_20',['How the NamespaceRegistry Works',['../integrating_extensions_page.html#namespace_registry',1,'']]],
  ['the_20nwbfile_21',['2. Create the NWBFile',['../workflow.html#create_nwbfile',1,'']]],
  ['the_20recording_22',['5. Start the recording.',['../workflow.html#start_recording',1,'']]],
  ['the_20recording_20and_20finalize_20the_20file_23',['7. Stop the recording and finalize the file.',['../workflow.html#stop_recording',1,'']]],
  ['the_20recording_20metadata_24',['3. Create the recording metadata',['../workflow.html#create_recmeta',1,'']]],
  ['the_20recording_20position_25',['Resetting the recording position',['../workflow.html#advanced_recording_workflow_reset',1,'']]],
  ['the_20registeredtype_20registry_26',['How to Use the RegisteredType Registry',['../read_design_page.html#use_registered_type_registry',1,'']]],
  ['the_20schema_27',['Updating the schema',['../nwb_schema_page.html#dev_docs_updating_nwb_schema_section',1,'']]],
  ['the_20schema_20header_20files_28',['Generating the schema header files',['../nwb_schema_page.html#dev_docs_generating_nwb_schema_headers_section',1,'']]],
  ['the_20schema_20of_20the_20extension_29',['Step 1: Get the Schema of the Extension',['../integrating_extensions_page.html#labmetadata_extension_schema',1,'']]],
  ['the_20schema_20to_20c_30',['Step 2: Convert the Schema to C++',['../integrating_extensions_page.html#labmetadata_extension_cpp_generation',1,'']]],
  ['the_20type_20registry_31',['Example: Using the type registry',['../read_design_page.html#use_registered_type_registry_example',1,'']]],
  ['the_20type_20registry_20in_20registeredtype_20works_32',['How the Type Registry in RegisteredType Works',['../read_design_page.html#type_registry',1,'']]],
  ['timeseries_20convenience_20methods_20for_20consistent_20recording_33',['TimeSeries Convenience Methods for Consistent Recording',['../record_design_page.html#record_design_sec_timeseries',1,'']]],
  ['to_20c_34',['Step 2: Convert the Schema to C++',['../integrating_extensions_page.html#labmetadata_extension_cpp_generation',1,'']]],
  ['to_20implement_20a_20registeredtype_35',['How to Implement a RegisteredType',['../registered_type_page.html#implement_registered_type',1,'']]],
  ['to_20implement_20a_20registeredtype_20with_20a_20custom_20type_20name_36',['How to implement a RegisteredType with a custom type name',['../registered_type_page.html#using_registered_subclass_with_typename',1,'']]],
  ['to_20integrate_20a_20new_20namespace_37',['How to Integrate a New Namespace',['../integrating_extensions_page.html#integrate_namespace',1,'']]],
  ['to_20neurodata_5ftype_20objects_38',['DEFINE_REFERENCED_REGISTERED_FIELD: Defining read methods for references to neurodata_type objects',['../registered_type_page.html#use_the_define_referenced_registered_field_macro',1,'']]],
  ['to_20recordingobjects_39',['4. Create datasets and add to RecordingObjects',['../workflow.html#create_datasets',1,'']]],
  ['to_20use_20the_20registeredtype_20registry_40',['How to Use the RegisteredType Registry',['../read_design_page.html#use_registered_type_registry',1,'']]],
  ['type_41',['Example: Implementing a New Type',['../registered_type_page.html#implement_registered_type_example',1,'']]],
  ['type_42',['Working with fields with unknown data type',['../read_page.html#read_example_variant_data',1,'']]],
  ['type_20🔧_43',['Implementing a Registered Type 🔧',['../registered_type_page.html',1,'devdocs']]],
  ['type_20name_44',['How to implement a RegisteredType with a custom type name',['../registered_type_page.html#using_registered_subclass_with_typename',1,'']]],
  ['type_20registry_45',['Example: Using the type registry',['../read_design_page.html#use_registered_type_registry_example',1,'']]],
  ['type_20registry_20in_20registeredtype_20works_46',['How the Type Registry in RegisteredType Works',['../read_design_page.html#type_registry',1,'']]],
  ['types_20command_47',['Using the generate-types command',['../registered_type_page.html#using_schematype_to_aqnwb',1,'']]]
];
