var searchData=
[
  ['a_20base_20class_20and_20templated_20child_20class_0',['Using a base class and templated child class',['../registered_type_page.html#implement_templated_registered_type_two_class',1,'']]],
  ['a_20custom_20hdf5_20installation_1',['Using a custom HDF5 installation',['../dev_install_page.html#devbuild_custom_hdf5_sec',1,'']]],
  ['a_20custom_20type_20name_2',['How to implement a RegisteredType with a custom type name',['../registered_type_page.html#using_registered_subclass_with_typename',1,'']]],
  ['a_20file_20from_20s3_3',['Opening a file from S3',['../reads3_page.html#reads3_ros3_open',1,'']]],
  ['a_20namespace_4',['Registering a Namespace',['../integrating_extensions_page.html#register_namespace',1,'']]],
  ['a_20new_20namespace_5',['How to Integrate a New Namespace',['../integrating_extensions_page.html#integrate_namespace',1,'']]],
  ['a_20new_20type_6',['Example: Implementing a New Type',['../registered_type_page.html#implement_registered_type_example',1,'']]],
  ['a_20newer_20c_20standard_20version_7',['Selecting a newer C++ standard version',['../dev_install_page.html#devbuild_cpp_std_sec',1,'']]],
  ['a_20processingmodule_8',['3. Create a ProcessingModule',['../links.html#link_processing',1,'']]],
  ['a_20recording_20workflow_9',['Overview of a recording workflow',['../workflow.html#recording_workflow',1,'']]],
  ['a_20registered_20type_20🔧_10',['Implementing a Registered Type 🔧',['../registered_type_page.html',1,'devdocs']]],
  ['a_20registeredtype_11',['How to Implement a RegisteredType',['../registered_type_page.html#implement_registered_type',1,'']]],
  ['a_20registeredtype_20with_20a_20custom_20type_20name_12',['How to implement a RegisteredType with a custom type name',['../registered_type_page.html#using_registered_subclass_with_typename',1,'']]],
  ['a_20release_13',['Making a Release',['../release_workflow.html',1,'devdocs']]],
  ['a_20release_20branch_14',['1. Create a Release Branch',['../release_workflow.html#release_steps_1',1,'']]],
  ['a_20single_20templated_20class_15',['Using a single templated class',['../registered_type_page.html#implement_templated_registered_type_single_class',1,'']]],
  ['acquiring_20data_20📊_16',['Acquiring Data 📊',['../workflow.html',1,'userdocs']]],
  ['add_20to_20recordingobjects_17',['4. Create datasets and add to RecordingObjects',['../workflow.html#create_datasets',1,'']]],
  ['advanced_3a_20recording_20individual_20datasets_18',['Advanced: Recording individual datasets',['../workflow.html#advanced_recording_workflow',1,'']]],
  ['after_20pr_20merge_19',['6. Tag the Release (after PR merge)',['../release_workflow.html#release_steps_6',1,'']]],
  ['aligned_20timeseries_20',['Use Case: Time-Aligned TimeSeries',['../links.html#link_use_case',1,'']]],
  ['all_20channels_20at_20once_20interleaved_20data_21',['Writing all channels at once (interleaved data)',['../workflow.html#write_data_allchannels',1,'']]],
  ['all_20neurodata_5ftypes_22',['Step 3: Create RegisteredType Classes for all neurodata_types',['../integrating_extensions_page.html#labmetadata_extension_registered_type',1,'']]],
  ['an_20existing_20file_20for_20reading_23',['Opening an existing file for reading',['../read_page.html#read_example_open',1,'']]],
  ['an_20nwb_20file_20with_20swmr_20mode_24',['Writing an NWB file with SWMR mode',['../hdf5io.html#hdf5io_swmr_workflow',1,'']]],
  ['analysis_20cppcheck_25',['Static Analysis (Cppcheck)',['../testing.html#testing_cppcheck',1,'']]],
  ['and_20add_20to_20recordingobjects_26',['4. Create datasets and add to RecordingObjects',['../workflow.html#create_datasets',1,'']]],
  ['and_20attributes_27',['Reading datasets and attributes',['../read_design_page.html#read_design_sec_read_date',1,'']]],
  ['and_20compression_28',['I/O Filters and Compression',['../hdf5io.html#hdf5io_filters',1,'']]],
  ['and_20data_29',['Reading objects and data',['../reads3_page.html#reads3_ros3_read',1,'']]],
  ['and_20finalize_20the_20file_30',['7. Stop the recording and finalize the file',['../workflow.html#stop_recording',1,'']]],
  ['and_20i_20o_20filters_20in_20aqnwb_31',['Using Chunking and I/O Filters in AqNWB',['../hdf5io.html#hdf5io_filters_usage',1,'']]],
  ['and_20memory_20management_32',['Object and memory management',['../record_design_page.html#record_design_object_memory_management',1,'']]],
  ['and_20processing_20data_33',['Reading and Processing Data',['../read_design_page.html#read_design_example_read',1,'']]],
  ['and_20push_20changes_34',['3. Commit and Push Changes',['../release_workflow.html#release_steps_3',1,'']]],
  ['and_20templated_20child_20class_35',['Using a base class and templated child class',['../registered_type_page.html#implement_templated_registered_type_two_class',1,'']]],
  ['and_20test_36',['Configure, Build and Test',['../dev_install_page.html#configure_build_test',1,'']]],
  ['and_20write_20methods_20for_20datasets_37',['DEFINE_DATASET_FIELD: Creating read and write methods for datasets',['../registered_type_page.html#use_the_define_dataset_field_macro',1,'']]],
  ['and_20writing_20data_38',['Creating and Writing Data',['../read_design_page.html#read_design_example_create',1,'']]],
  ['aqnwb_39',['AqNWB',['../user_demos.html#demos_inspect_electrical_series',1,'Inspect Electrical Series Data using AqNWB'],['../dev_install_page.html#dev_install_aqnwb_sec',1,'Installing AqNWB'],['../user_demos.html#demos_labmetadata_extension',1,'Integrating LabMetaData Extension with AqNWB'],['../hdf5io.html#hdf5io_filters_usage',1,'Using Chunking and I/O Filters in AqNWB']]],
  ['aqnwb_20use_20smwr_20mode_40',['Why does AqNWB use SMWR mode?',['../hdf5io.html#hdf5io_swmr_features',1,'']]],
  ['arbitrary_20fields_41',['Reading arbitrary fields',['../read_page.html#read_example_arbitrary',1,'']]],
  ['at_20once_20interleaved_20data_42',['Writing all channels at once (interleaved data)',['../workflow.html#write_data_allchannels',1,'']]],
  ['attributes_43',['attributes',['../registered_type_page.html#use_the_define_attribute_field_macro',1,'DEFINE_ATTRIBUTE_FIELD: Creating read methods for attributes'],['../read_design_page.html#read_design_sec_read_date',1,'Reading datasets and attributes']]],
  ['automated_20tests_20on_20github_44',['Automated tests on GitHub',['../testing.html#testing_github',1,'']]]
];
