var searchData=
[
  ['a_20base_20class_20and_20templated_20child_20class_0',['Using a base class and templated child class',['../registered_type_page.html#implement_templated_registered_type_two_class',1,'']]],
  ['a_20coded_20column_1',['Setup: create the EventsTable with a coded column',['../events.html#events_meanings_setup',1,'']]],
  ['a_20custom_20hdf5_20installation_2',['Using a custom HDF5 installation',['../dev_install_page.html#devbuild_custom_hdf5_sec',1,'']]],
  ['a_20custom_20type_20name_3',['How to implement a RegisteredType with a custom type name',['../registered_type_page.html#using_registered_subclass_with_typename',1,'']]],
  ['a_20file_20from_20s3_4',['Opening a file from S3',['../reads3_page.html#reads3_ros3_open',1,'']]],
  ['a_20meaningstable_5',['Annotating columns with a MeaningsTable',['../events.html#events_meanings',1,'']]],
  ['a_20namespace_6',['Registering a Namespace',['../integrating_extensions_page.html#register_namespace',1,'']]],
  ['a_20new_20namespace_7',['How to Integrate a New Namespace',['../integrating_extensions_page.html#integrate_namespace',1,'']]],
  ['a_20new_20type_8',['Example: Implementing a New Type',['../registered_type_page.html#implement_registered_type_example',1,'']]],
  ['a_20newer_20c_20standard_20version_9',['Selecting a newer C++ standard version',['../dev_install_page.html#devbuild_cpp_std_sec',1,'']]],
  ['a_20processingmodule_10',['3. Create a ProcessingModule',['../links.html#link_processing',1,'']]],
  ['a_20recording_20workflow_11',['Overview of a recording workflow',['../workflow.html#recording_workflow',1,'']]],
  ['a_20registered_20type_20🔧_12',['Implementing a Registered Type 🔧',['../registered_type_page.html',1,'devdocs']]],
  ['a_20registeredtype_13',['How to Implement a RegisteredType',['../registered_type_page.html#implement_registered_type',1,'']]],
  ['a_20registeredtype_20with_20a_20custom_20type_20name_14',['How to implement a RegisteredType with a custom type name',['../registered_type_page.html#using_registered_subclass_with_typename',1,'']]],
  ['a_20release_15',['Making a Release',['../release_workflow.html',1,'devdocs']]],
  ['a_20release_20branch_16',['1. Create a Release Branch',['../release_workflow.html#release_steps_1',1,'']]],
  ['a_20single_20templated_20class_17',['Using a single templated class',['../registered_type_page.html#implement_templated_registered_type_single_class',1,'']]],
  ['acquiring_20data_20📊_18',['Acquiring Data 📊',['../workflow.html',1,'userdocs']]],
  ['acquiring_20event_20data_20📋_19',['Acquiring Event Data 📋',['../events.html',1,'userdocs']]],
  ['acquisition_20',['acquisition',['../events.html#events_rowbased',1,'Pattern 1: Row-based acquisition'],['../time_intervals.html#time_intervals_rowbased',1,'Pattern 1: Row-based acquisition'],['../events.html#events_colbased',1,'Pattern 2: Column-based (bulk) acquisition'],['../time_intervals.html#time_intervals_colbased',1,'Pattern 2: Column-based (bulk) acquisition']]],
  ['add_20data_20to_20columns_21',['Add data to columns',['../events.html#events_colbased_adddata',1,'Add data to columns'],['../time_intervals.html#time_intervals_colbased_adddata',1,'Add data to columns']]],
  ['add_20rows_22',['Add rows',['../events.html#events_rowbased_addrow',1,'Add rows'],['../time_intervals.html#time_intervals_rowbased_addrow',1,'Add rows']]],
  ['add_20to_20recordingobjects_23',['4. Create datasets and add to RecordingObjects',['../workflow.html#create_datasets',1,'']]],
  ['advanced_3a_20recording_20individual_20datasets_24',['Advanced: Recording individual datasets',['../workflow.html#advanced_recording_workflow',1,'']]],
  ['after_20pr_20merge_25',['6. Tag the Release (after PR merge)',['../release_workflow.html#release_steps_6',1,'']]],
  ['aligned_20timeseries_26',['Use Case: Time-Aligned TimeSeries',['../links.html#link_use_case',1,'']]],
  ['all_20channels_20at_20once_20interleaved_20data_27',['Writing all channels at once (interleaved data)',['../workflow.html#write_data_allchannels',1,'']]],
  ['all_20neurodata_5ftypes_28',['Step 3: Create RegisteredType Classes for all neurodata_types',['../integrating_extensions_page.html#labmetadata_extension_registered_type',1,'']]],
  ['an_20existing_20file_20for_20reading_29',['Opening an existing file for reading',['../read_page.html#read_example_open',1,'']]],
  ['an_20nwb_20file_20with_20swmr_20mode_30',['Writing an NWB file with SWMR mode',['../hdf5io.html#hdf5io_swmr_workflow',1,'']]],
  ['analysis_20cppcheck_31',['Static Analysis (Cppcheck)',['../testing.html#testing_cppcheck',1,'']]],
  ['and_20add_20to_20recordingobjects_32',['4. Create datasets and add to RecordingObjects',['../workflow.html#create_datasets',1,'']]],
  ['and_20attributes_33',['Reading datasets and attributes',['../read_design_page.html#read_design_sec_read_date',1,'']]],
  ['and_20best_20practices_34',['Tips and best practices',['../events.html#events_tips',1,'']]],
  ['and_20compression_35',['I/O Filters and Compression',['../hdf5io.html#hdf5io_filters',1,'']]],
  ['and_20create_20the_20eventstable_36',['3. Configure and create the EventsTable',['../events.html#events_configure_table',1,'']]],
  ['and_20create_20the_20timeintervals_20table_37',['3. Configure and create the TimeIntervals table',['../time_intervals.html#time_intervals_configure_table',1,'']]],
  ['and_20data_38',['Reading objects and data',['../reads3_page.html#reads3_ros3_read',1,'']]],
  ['and_20finalize_20the_20file_39',['7. Stop the recording and finalize the file',['../workflow.html#stop_recording',1,'']]],
  ['and_20i_20o_20filters_20in_20aqnwb_40',['Using Chunking and I/O Filters in AqNWB',['../hdf5io.html#hdf5io_filters_usage',1,'']]],
  ['and_20memory_20management_41',['Object and memory management',['../record_design_page.html#record_design_object_memory_management',1,'']]],
  ['and_20processing_20data_42',['Reading and Processing Data',['../read_design_page.html#read_design_example_read',1,'']]],
  ['and_20push_20changes_43',['3. Commit and Push Changes',['../release_workflow.html#release_steps_3',1,'']]],
  ['and_20table_20creation_44',['and table creation',['../events.html#events_setup',1,'Setup: I/O, NWBFile, and table creation'],['../time_intervals.html#time_intervals_setup',1,'Setup: I/O, NWBFile, and table creation']]],
  ['and_20templated_20child_20class_45',['Using a base class and templated child class',['../registered_type_page.html#implement_templated_registered_type_two_class',1,'']]],
  ['and_20test_46',['Configure, Build and Test',['../dev_install_page.html#configure_build_test',1,'']]],
  ['and_20write_20methods_20for_20datasets_47',['DEFINE_DATASET_FIELD: Creating read and write methods for datasets',['../registered_type_page.html#use_the_define_dataset_field_macro',1,'']]],
  ['and_20writing_20data_48',['Creating and Writing Data',['../read_design_page.html#read_design_example_create',1,'']]],
  ['annotating_20columns_20with_20a_20meaningstable_49',['Annotating columns with a MeaningsTable',['../events.html#events_meanings',1,'']]],
  ['annotating_20time_20intervals_20⏱️_50',['Annotating Time Intervals ⏱️',['../time_intervals.html',1,'userdocs']]],
  ['aqnwb_51',['AqNWB',['../user_demos.html#demos_inspect_electrical_series',1,'Inspect Electrical Series Data using AqNWB'],['../dev_install_page.html#dev_install_aqnwb_sec',1,'Installing AqNWB'],['../user_demos.html#demos_labmetadata_extension',1,'Integrating LabMetaData Extension with AqNWB'],['../hdf5io.html#hdf5io_filters_usage',1,'Using Chunking and I/O Filters in AqNWB']]],
  ['aqnwb_20use_20smwr_20mode_52',['Why does AqNWB use SMWR mode?',['../hdf5io.html#hdf5io_swmr_features',1,'']]],
  ['arbitrary_20fields_53',['Reading arbitrary fields',['../read_page.html#read_example_arbitrary',1,'']]],
  ['at_20once_20interleaved_20data_54',['Writing all channels at once (interleaved data)',['../workflow.html#write_data_allchannels',1,'']]],
  ['attributes_55',['attributes',['../registered_type_page.html#use_the_define_attribute_field_macro',1,'DEFINE_ATTRIBUTE_FIELD: Creating read methods for attributes'],['../read_design_page.html#read_design_sec_read_date',1,'Reading datasets and attributes']]],
  ['automated_20tests_20on_20github_56',['Automated tests on GitHub',['../testing.html#testing_github',1,'']]]
];
