var searchData=
[
  ['tag_20the_20release_20after_20pr_20merge_0',['6. Tag the Release (after PR merge)',['../release_workflow.html#release_steps_6',1,'']]],
  ['target_20options_1',['Target options',['../dev_install_page.html#devbuild_target_options_subsubsec',1,'']]],
  ['targets_2',['Developer Mode Targets',['../dev_install_page.html#devbuild_dev_mode_targets_subsec',1,'']]],
  ['templated_20child_20class_3',['Using a base class and templated child class',['../registered_type_page.html#implement_templated_registered_type_two_class',1,'']]],
  ['templated_20class_4',['Using a single templated class',['../registered_type_page.html#implement_templated_registered_type_single_class',1,'']]],
  ['templated_20registeredtype_20classes_5',['Templated RegisteredType Classes',['../registered_type_page.html#implement_templated_registered_type',1,'']]],
  ['templated_20registeredtype_20classes_6',['Reading templated RegisteredType classes',['../read_design_page.html#read_design_templates',1,'']]],
  ['test_7',['Configure, Build and Test',['../dev_install_page.html#configure_build_test',1,'']]],
  ['test_20locally_8',['4. Test Locally',['../release_workflow.html#release_steps_4',1,'']]],
  ['testing_20🛡️_9',['Testing 🛡️',['../testing.html',1,'devdocs']]],
  ['testing_20registeredtypes_10',['Testing RegisteredTypes',['../registered_type_page.html#implement_registered_type_unit_tests',1,'']]],
  ['testing_20the_20example_20code_11',['Testing the Example Code',['../dev_docs_page.html#dev_docs_codeexamples_run_sec',1,'']]],
  ['tests_12',['Tests',['../testing.html#testing_unit_run',1,'Running Unit Tests'],['../testing.html#testing_unit',1,'Unit Tests']]],
  ['tests_20on_20github_13',['Automated tests on GitHub',['../testing.html#testing_github',1,'']]],
  ['the_20define_5fdataset_5ffield_20macro_20for_20recording_14',['The DEFINE_DATASET_FIELD Macro for Recording',['../record_design_page.html#record_design_sec_define_dataset_field',1,'']]],
  ['the_20docs_15',['Building the Docs',['../dev_docs_page.html#dev_docs_requirements_sec',1,'']]],
  ['the_20example_20code_16',['the Example Code',['../dev_docs_page.html#dev_docs_codeexamples_def_sec',1,'Creating the Example Code'],['../dev_docs_page.html#dev_docs_codeexamples_run_sec',1,'Testing the Example Code']]],
  ['the_20extension_17',['the Extension',['../integrating_extensions_page.html#labmetadata_extension_schema',1,'Step 1: Get the Schema of the Extension'],['../integrating_extensions_page.html#labmetadata_extension_usage',1,'Step 4: Using the Extension']]],
  ['the_20extracellular_20recording_20metadata_18',['Create the extracellular recording metadata',['../workflow.html#create_recmeta_ecephys',1,'']]],
  ['the_20file_19',['7. Stop the recording and finalize the file.',['../workflow.html#stop_recording',1,'']]],
  ['the_20generate_20types_20command_20',['Using the generate-types command',['../registered_type_page.html#using_schematype_to_aqnwb',1,'']]],
  ['the_20i_20o_20object_21',['1. Create the I/O object',['../workflow.html#create_io',1,'']]],
  ['the_20linked_20timeseries_22',['4. Create the Linked TimeSeries',['../links.html#link_linked',1,'']]],
  ['the_20namespaceregistry_20works_23',['How the NamespaceRegistry Works',['../integrating_extensions_page.html#namespace_registry',1,'']]],
  ['the_20nwbfile_24',['2. Create the NWBFile',['../workflow.html#create_nwbfile',1,'']]],
  ['the_20original_20series_25',['5. Link to the Original Series',['../links.html#link_reference',1,'']]],
  ['the_20original_20timeseries_26',['2. Create the Original TimeSeries',['../links.html#link_original',1,'']]],
  ['the_20recording_27',['5. Start the recording.',['../workflow.html#start_recording',1,'']]],
  ['the_20recording_20and_20finalize_20the_20file_28',['7. Stop the recording and finalize the file.',['../workflow.html#stop_recording',1,'']]],
  ['the_20recording_20metadata_29',['3. Create the recording metadata',['../workflow.html#create_recmeta',1,'']]],
  ['the_20recording_20position_30',['Resetting the recording position',['../workflow.html#advanced_recording_workflow_reset',1,'']]],
  ['the_20registeredtype_20registry_31',['How to Use the RegisteredType Registry',['../read_design_page.html#use_registered_type_registry',1,'']]],
  ['the_20release_20after_20pr_20merge_32',['6. Tag the Release (after PR merge)',['../release_workflow.html#release_steps_6',1,'']]],
  ['the_20schema_33',['Updating the schema',['../nwb_schema_page.html#dev_docs_updating_nwb_schema_section',1,'']]],
  ['the_20schema_20header_20files_34',['Generating the schema header files',['../nwb_schema_page.html#dev_docs_generating_nwb_schema_headers_section',1,'']]],
  ['the_20schema_20of_20the_20extension_35',['Step 1: Get the Schema of the Extension',['../integrating_extensions_page.html#labmetadata_extension_schema',1,'']]],
  ['the_20schema_20to_20c_36',['Step 2: Convert the Schema to C++',['../integrating_extensions_page.html#labmetadata_extension_cpp_generation',1,'']]],
  ['the_20type_20registry_37',['Example: Using the type registry',['../read_design_page.html#use_registered_type_registry_example',1,'']]],
  ['the_20type_20registry_20in_20registeredtype_20works_38',['How the Type Registry in RegisteredType Works',['../read_design_page.html#type_registry',1,'']]],
  ['time_20aligned_20timeseries_39',['Use Case: Time-Aligned TimeSeries',['../links.html#link_use_case',1,'']]],
  ['timeseries_40',['TimeSeries',['../links.html#link_original',1,'2. Create the Original TimeSeries'],['../links.html#link_linked',1,'4. Create the Linked TimeSeries'],['../links.html#link_use_case',1,'Use Case: Time-Aligned TimeSeries']]],
  ['timeseries_20convenience_20methods_20for_20consistent_20recording_41',['TimeSeries Convenience Methods for Consistent Recording',['../record_design_page.html#record_design_sec_timeseries',1,'']]],
  ['to_20c_42',['Step 2: Convert the Schema to C++',['../integrating_extensions_page.html#labmetadata_extension_cpp_generation',1,'']]],
  ['to_20implement_20a_20registeredtype_43',['How to Implement a RegisteredType',['../registered_type_page.html#implement_registered_type',1,'']]],
  ['to_20implement_20a_20registeredtype_20with_20a_20custom_20type_20name_44',['How to implement a RegisteredType with a custom type name',['../registered_type_page.html#using_registered_subclass_with_typename',1,'']]],
  ['to_20integrate_20a_20new_20namespace_45',['How to Integrate a New Namespace',['../integrating_extensions_page.html#integrate_namespace',1,'']]],
  ['to_20neurodata_5ftype_20objects_46',['DEFINE_REFERENCED_REGISTERED_FIELD: Defining read methods for references to neurodata_type objects',['../registered_type_page.html#use_the_define_referenced_registered_field_macro',1,'']]],
  ['to_20recordingobjects_47',['4. Create datasets and add to RecordingObjects',['../workflow.html#create_datasets',1,'']]],
  ['to_20the_20original_20series_48',['5. Link to the Original Series',['../links.html#link_reference',1,'']]],
  ['to_20use_20the_20registeredtype_20registry_49',['How to Use the RegisteredType Registry',['../read_design_page.html#use_registered_type_registry',1,'']]],
  ['type_50',['Example: Implementing a New Type',['../registered_type_page.html#implement_registered_type_example',1,'']]],
  ['type_51',['Working with fields with unknown data type',['../read_page.html#read_example_variant_data',1,'']]],
  ['type_20🔧_52',['Implementing a Registered Type 🔧',['../registered_type_page.html',1,'devdocs']]],
  ['type_20name_53',['How to implement a RegisteredType with a custom type name',['../registered_type_page.html#using_registered_subclass_with_typename',1,'']]],
  ['type_20registry_54',['Example: Using the type registry',['../read_design_page.html#use_registered_type_registry_example',1,'']]],
  ['type_20registry_20in_20registeredtype_20works_55',['How the Type Registry in RegisteredType Works',['../read_design_page.html#type_registry',1,'']]],
  ['types_20command_56',['Using the generate-types command',['../registered_type_page.html#using_schematype_to_aqnwb',1,'']]]
];
