var searchData=
[
  ['o_20📂_0',['HDF5 I/O 📂',['../hdf5io.html',1,'userdocs']]],
  ['o_20convenience_20utilities_1',['NWB I/O convenience utilities',['../record_design_page.html#record_design_nwbio_utils',1,'']]],
  ['o_20filters_20and_20compression_2',['I/O Filters and Compression',['../hdf5io.html#hdf5io_filters',1,'']]],
  ['o_20filters_20in_20aqnwb_3',['Using Chunking and I/O Filters in AqNWB',['../hdf5io.html#hdf5io_filters_usage',1,'']]],
  ['o_20nwbfile_20and_20table_20creation_4',['O NWBFile and table creation',['../events.html#events_setup',1,'Setup: I/O, NWBFile, and table creation'],['../time_intervals.html#time_intervals_setup',1,'Setup: I/O, NWBFile, and table creation']]],
  ['o_20object_5',['O object',['../events.html#events_io',1,'1. Create the I/O object'],['../time_intervals.html#time_intervals_io',1,'1. Create the I/O object'],['../workflow.html#create_io',1,'1. Create the I/O object']]],
  ['object_6',['object',['../events.html#events_io',1,'1. Create the I/O object'],['../time_intervals.html#time_intervals_io',1,'1. Create the I/O object'],['../workflow.html#create_io',1,'1. Create the I/O object']]],
  ['object_20and_20memory_20management_7',['Object and memory management',['../record_design_page.html#record_design_object_memory_management',1,'']]],
  ['objects_8',['objects',['../registered_type_page.html#use_the_define_referenced_registered_field_macro',1,'DEFINE_REFERENCED_REGISTERED_FIELD: Defining read methods for references to neurodata_type objects'],['../registered_type_page.html#use_the_define_registered_field_macro',1,'DEFINE_REGISTERED_FIELD: Defining read methods for neurodata_type objects'],['../registered_type_page.html#use_the_define_unnamed_registered_field_macro',1,'DEFINE_UNNAMED_REGISTERED_FIELD: Defining read methods for unnamed neurodata_type objects'],['../read_page.html#read_example_dynamic_table',1,'Reading data from DynamicTable objects'],['../read_page.html#read_example_read',1,'Reading data from RegisteredType objects'],['../read_page.html#read_example_predefined_registered_type',1,'Reading known RegisteredType objects'],['../read_design_page.html#reading_neurodata_type_objects',1,'Reading neurodata_type objects'],['../read_page.html#read_example_search',1,'Searching for RegisteredType objects']]],
  ['objects_20and_20data_9',['Reading objects and data',['../reads3_page.html#reads3_ros3_read',1,'']]],
  ['of_20a_20recording_20workflow_10',['Overview of a recording workflow',['../workflow.html#recording_workflow',1,'']]],
  ['of_20conduct_11',['Code of Conduct',['../legal_page.html#legal_code_of_conduct',1,'']]],
  ['of_20data_20read_20📤_12',['Implementation of Data Read 📤',['../read_design_page.html',1,'devdocs']]],
  ['of_20data_20recording_20📊_13',['Implementation of Data Recording 📊',['../record_design_page.html',1,'devdocs']]],
  ['of_20register_5fsubclass_5fwith_5ftypename_14',['Limitations of REGISTER_SUBCLASS_WITH_TYPENAME',['../registered_type_page.html#limitations_registered_subclass_with_typename',1,'']]],
  ['of_20the_20extension_15',['Step 1: Get the Schema of the Extension',['../integrating_extensions_page.html#labmetadata_extension_schema',1,'']]],
  ['on_20github_16',['on GitHub',['../testing.html#testing_github',1,'Automated tests on GitHub'],['../testing.html#testing_cppcheck_github',1,'Cppcheck on GitHub']]],
  ['once_20interleaved_20data_17',['Writing all channels at once (interleaved data)',['../workflow.html#write_data_allchannels',1,'']]],
  ['open_20pull_20request_18',['5. Open Pull Request',['../release_workflow.html#release_steps_5',1,'']]],
  ['opening_20a_20file_20from_20s3_19',['Opening a file from S3',['../reads3_page.html#reads3_ros3_open',1,'']]],
  ['opening_20an_20existing_20file_20for_20reading_20',['Opening an existing file for reading',['../read_page.html#read_example_open',1,'']]],
  ['optimizing_20data_20layout_21',['Optimizing Data Layout',['../hdf5io.html#hdf5io_data_layout',1,'']]],
  ['options_22',['Target options',['../dev_install_page.html#devbuild_target_options_subsubsec',1,'']]],
  ['original_20series_23',['5. Link to the Original Series',['../links.html#link_reference',1,'']]],
  ['original_20timeseries_24',['2. Create the Original TimeSeries',['../links.html#link_original',1,'']]],
  ['overview_25',['Overview',['../index.html',1,'Overview'],['../events.html#events_overview',1,'Overview'],['../links.html#link_overview',1,'Overview'],['../time_intervals.html#time_intervals_overview',1,'Overview']]],
  ['overview_20of_20a_20recording_20workflow_26',['Overview of a recording workflow',['../workflow.html#recording_workflow',1,'']]]
];
