var searchData=
[
  ['target_20options_0',['Target options',['../dev_install_page.html#devbuild_target_options_subsubsec',1,'']]],
  ['targets_1',['Developer Mode Targets',['../dev_install_page.html#devbuild_dev_mode_targets_subsec',1,'']]],
  ['templated_20child_20class_2',['Using a base class and templated child class',['../registered_type_page.html#implement_templated_registered_type_two_class',1,'']]],
  ['templated_20class_3',['Using a single templated class',['../registered_type_page.html#implement_templated_registered_type_single_class',1,'']]],
  ['templated_20registeredtype_20classes_4',['Templated RegisteredType Classes',['../registered_type_page.html#implement_templated_registered_type',1,'']]],
  ['templated_20registeredtype_20classes_5',['Reading templated RegisteredType classes',['../read_design_page.html#read_design_templates',1,'']]],
  ['test_6',['Configure, Build and Test',['../dev_install_page.html#configure_build_test',1,'']]],
  ['testing_7',['Testing',['../testing.html',1,'devdocs']]],
  ['testing_20registeredtypes_8',['Testing RegisteredTypes',['../registered_type_page.html#implement_registered_type_unit_tests',1,'']]],
  ['testing_20the_20example_20code_9',['Testing the Example Code',['../dev_docs_page.html#dev_docs_codeexamples_run_sec',1,'']]],
  ['tests_10',['Tests',['../testing.html#testing_unit_run',1,'Running Unit Tests'],['../testing.html#testing_unit',1,'Unit Tests']]],
  ['tests_20on_20github_11',['Automated tests on GitHub',['../testing.html#testing_github',1,'']]],
  ['the_20docs_12',['Building the Docs',['../dev_docs_page.html#dev_docs_requirements_sec',1,'']]],
  ['the_20documentation_13',['Navigating the Documentation',['../index.html#mainpage_navigation',1,'']]],
  ['the_20example_20code_14',['the Example Code',['../dev_docs_page.html#dev_docs_codeexamples_def_sec',1,'Creating the Example Code'],['../dev_docs_page.html#dev_docs_codeexamples_run_sec',1,'Testing the Example Code']]],
  ['the_20extension_15',['the Extension',['../integrating_extensions_page.html#labmetadata_extension_schema',1,'Step 1: Get the Schema of the Extension'],['../integrating_extensions_page.html#labmetadata_extension_usage',1,'Step 4: Using the Extension']]],
  ['the_20extracellular_20recording_20metadata_16',['Create the extracellular recording metadata',['../workflow.html#create_recmeta_ecephys',1,'']]],
  ['the_20file_17',['8. Stop the recording and finalize the file.',['../workflow.html#stop_recording',1,'']]],
  ['the_20i_20o_20object_18',['1. Create the I/O object.',['../workflow.html#create_io',1,'']]],
  ['the_20namespaceregistry_20works_19',['How the NamespaceRegistry Works',['../integrating_extensions_page.html#namespace_registry',1,'']]],
  ['the_20nwbfile_20',['3. Create the NWBFile',['../workflow.html#create_nwbfile',1,'']]],
  ['the_20recording_21',['6. Start the recording.',['../workflow.html#start_recording',1,'']]],
  ['the_20recording_20and_20finalize_20the_20file_22',['8. Stop the recording and finalize the file.',['../workflow.html#stop_recording',1,'']]],
  ['the_20recording_20metadata_23',['4. Create the recording metadata',['../workflow.html#create_recmeta',1,'']]],
  ['the_20recordingcontainer_20object_24',['2. Create the RecordingContainer object.',['../workflow.html#create_recording_container',1,'']]],
  ['the_20registeredtype_20registry_25',['How to Use the RegisteredType Registry',['../read_design_page.html#use_registered_type_registry',1,'']]],
  ['the_20schema_26',['Updating the schema',['../nwb_schema_page.html#dev_docs_updating_nwb_schema_section',1,'']]],
  ['the_20schema_20header_20files_27',['Generating the schema header files',['../nwb_schema_page.html#dev_docs_generating_nwb_schema_headers_section',1,'']]],
  ['the_20schema_20of_20the_20extension_28',['Step 1: Get the Schema of the Extension',['../integrating_extensions_page.html#labmetadata_extension_schema',1,'']]],
  ['the_20schema_20to_20c_29',['Step 2: Convert the Schema to C++',['../integrating_extensions_page.html#labmetadata_extension_cpp_generation',1,'']]],
  ['the_20type_20registry_30',['Example: Using the type registry',['../read_design_page.html#use_registered_type_registry_example',1,'']]],
  ['the_20type_20registry_20in_20registeredtype_20works_31',['How the Type Registry in RegisteredType Works',['../read_design_page.html#type_registry',1,'']]],
  ['to_20c_32',['Step 2: Convert the Schema to C++',['../integrating_extensions_page.html#labmetadata_extension_cpp_generation',1,'']]],
  ['to_20implement_20a_20registeredtype_33',['How to Implement a RegisteredType',['../registered_type_page.html#implement_registered_type',1,'']]],
  ['to_20implement_20a_20registeredtype_20with_20a_20custom_20type_20name_34',['How to implement a RegisteredType with a custom type name',['../registered_type_page.html#using_registered_subclass_with_typename',1,'']]],
  ['to_20integrate_20a_20new_20namespace_35',['How to Integrate a New Namespace',['../integrating_extensions_page.html#integrate_namespace',1,'']]],
  ['to_20neurodata_5ftype_20objects_36',['DEFINE_REFERENCED_REGISTERED_FIELD: Defining read methods for references to neurodata_type objects',['../registered_type_page.html#use_the_define_referenced_registered_field_macro',1,'']]],
  ['to_20recordingcontainers_37',['5. Create datasets and add to RecordingContainers.',['../workflow.html#create_datasets',1,'']]],
  ['to_20use_20the_20registeredtype_20registry_38',['How to Use the RegisteredType Registry',['../read_design_page.html#use_registered_type_registry',1,'']]],
  ['type_39',['Implementing a new Neurodata Type',['../registered_type_page.html',1,'devdocs']]],
  ['type_40',['type',['../registered_type_page.html#implement_registered_type_example',1,'Example: Implementing a new type'],['../read_page.html#read_example_variant_data',1,'Working with fields with unknown data type']]],
  ['type_20name_41',['How to implement a RegisteredType with a custom type name',['../registered_type_page.html#using_registered_subclass_with_typename',1,'']]],
  ['type_20registry_42',['Example: Using the type registry',['../read_design_page.html#use_registered_type_registry_example',1,'']]],
  ['type_20registry_20in_20registeredtype_20works_43',['How the Type Registry in RegisteredType Works',['../read_design_page.html#type_registry',1,'']]]
];
