var searchData=
[
  ['data_0',['Data',['../read_design_page.html#read_design_example_create',1,'Creating and Writing Data'],['../read_design_page.html#read_design_example_read',1,'Reading and Processing Data']]],
  ['data_1',['7. Write data.',['../workflow.html#write_data',1,'']]],
  ['data_20📊_2',['Acquiring Data 📊',['../workflow.html',1,'userdocs']]],
  ['data_20📤_3',['Reading Data 📤',['../read_page.html',1,'userdocs']]],
  ['data_20fields_4',['Reading predefined data fields',['../read_page.html#read_design_example_read_posthoc_read_field',1,'']]],
  ['data_20from_20registeredtype_20objects_5',['Reading data from RegisteredType objects',['../read_page.html#read_example_read',1,'']]],
  ['data_20layout_6',['Optimizing Data Layout',['../hdf5io.html#hdf5io_data_layout',1,'']]],
  ['data_20read_20📤_7',['Implementation of Data Read 📤',['../read_design_page.html',1,'devdocs']]],
  ['data_20type_8',['Working with fields with unknown data type',['../read_page.html#read_example_variant_data',1,'']]],
  ['data_20using_20aqnwb_9',['Inspect Electrical Series Data using AqNWB',['../user_demos.html#demos_inspect_electrical_series',1,'']]],
  ['datasets_20and_20add_20to_20recordingcontainers_10',['5. Create datasets and add to RecordingContainers.',['../workflow.html#create_datasets',1,'']]],
  ['datasets_20and_20attributes_11',['datasets and attributes',['../registered_type_page.html#use_the_define_field_macro',1,'DEFINE_FIELD: Creating read methods for datasets and attributes'],['../read_design_page.html#read_design_sec_read_date',1,'Reading datasets and attributes']]],
  ['define_5ffield_3a_20creating_20read_20methods_20for_20datasets_20and_20attributes_12',['DEFINE_FIELD: Creating read methods for datasets and attributes',['../registered_type_page.html#use_the_define_field_macro',1,'']]],
  ['define_5freferenced_5fregistered_5ffield_3a_20defining_20read_20methods_20for_20references_20to_20neurodata_5ftype_20objects_13',['DEFINE_REFERENCED_REGISTERED_FIELD: Defining read methods for references to neurodata_type objects',['../registered_type_page.html#use_the_define_referenced_registered_field_macro',1,'']]],
  ['define_5fregistered_5ffield_3a_20defining_20read_20methods_20for_20neurodata_5ftype_20objects_14',['DEFINE_REGISTERED_FIELD: Defining read methods for neurodata_type objects',['../registered_type_page.html#use_the_define_registered_field_macro',1,'']]],
  ['defining_20read_20methods_20for_20neurodata_5ftype_20objects_15',['DEFINE_REGISTERED_FIELD: Defining read methods for neurodata_type objects',['../registered_type_page.html#use_the_define_registered_field_macro',1,'']]],
  ['defining_20read_20methods_20for_20references_20to_20neurodata_5ftype_20objects_16',['DEFINE_REFERENCED_REGISTERED_FIELD: Defining read methods for references to neurodata_type objects',['../registered_type_page.html#use_the_define_referenced_registered_field_macro',1,'']]],
  ['demo_17',['LabMetaData Extension Demo',['../integrating_extensions_page.html#labmetadata_extension_demo',1,'']]],
  ['demos_20📝_18',['Demos 📝',['../user_demos.html',1,'userdocs']]],
  ['details_19',['Example Implementation Details',['../read_design_page.html#read_design_example',1,'']]],
  ['developer_20build_20',['Developer Build',['../dev_install_page.html#devbuild_sec',1,'']]],
  ['developer_20mode_20targets_21',['Developer Mode Targets',['../dev_install_page.html#devbuild_dev_mode_targets_subsec',1,'']]],
  ['developer_20presets_22',['Developer Presets',['../dev_install_page.html#devbuild_presets_subsec',1,'']]],
  ['developers_23',['For Developers',['../devdocs.html',1,'']]],
  ['disabled_24',['Workflow with SWMR disabled',['../hdf5io.html#hdf5io_noswmr_examples_without_swmr',1,'']]],
  ['docs_25',['Building the Docs',['../dev_docs_page.html#dev_docs_requirements_sec',1,'']]],
  ['documentation_20📚_26',['Documentation 📚',['../dev_docs_page.html',1,'Documentation 📚'],['../index.html#mainpage_navigation',1,'Documentation 📚']]],
  ['documentation_20pages_27',['Creating New Documentation Pages',['../dev_docs_page.html#dev_docs_creating',1,'']]],
  ['does_20aqnwb_20use_20smwr_20mode_28',['Why does AqNWB use SMWR mode?',['../hdf5io.html#hdf5io_swmr_features',1,'']]],
  ['dot_20graphs_29',['Creating Custom Dot Graphs',['../dev_docs_page.html#dev_docs_graphviz_sec',1,'']]],
  ['doxygen_30',['Including Code Examples in Doxygen',['../dev_docs_page.html#dev_docs_codeexamples_incl_sec',1,'']]]
];
