var searchData=
[
  ['a_20base_20class_20and_20templated_20child_20class_0',['Using a base class and templated child class',['../registered_type_page.html#implement_templated_registered_type_two_class',1,'']]],
  ['a_20custom_20hdf5_20installation_1',['Using a custom HDF5 installation',['../dev_install_page.html#devbuild_custom_hdf5_sec',1,'']]],
  ['a_20custom_20type_20name_2',['How to implement a RegisteredType with a custom type name',['../registered_type_page.html#using_registered_subclass_with_typename',1,'']]],
  ['a_20namespace_3',['Registering a Namespace',['../integrating_extensions_page.html#register_namespace',1,'']]],
  ['a_20new_20namespace_4',['How to Integrate a New Namespace',['../integrating_extensions_page.html#integrate_namespace',1,'']]],
  ['a_20new_20type_5',['Example: Implementing a New Type',['../registered_type_page.html#implement_registered_type_example',1,'']]],
  ['a_20newer_20c_20standard_20version_6',['Selecting a newer C++ standard version',['../dev_install_page.html#devbuild_cpp_std_sec',1,'']]],
  ['a_20processingmodule_7',['3. Create a ProcessingModule',['../links.html#link_processing',1,'']]],
  ['a_20recording_20workflow_8',['Overview of a recording workflow',['../workflow.html#recording_workflow',1,'']]],
  ['a_20registered_20type_20🔧_9',['Implementing a Registered Type 🔧',['../registered_type_page.html',1,'devdocs']]],
  ['a_20registeredtype_10',['How to Implement a RegisteredType',['../registered_type_page.html#implement_registered_type',1,'']]],
  ['a_20registeredtype_20with_20a_20custom_20type_20name_11',['How to implement a RegisteredType with a custom type name',['../registered_type_page.html#using_registered_subclass_with_typename',1,'']]],
  ['a_20single_20templated_20class_12',['Using a single templated class',['../registered_type_page.html#implement_templated_registered_type_single_class',1,'']]],
  ['acquiring_20data_20📊_13',['Acquiring Data 📊',['../workflow.html',1,'userdocs']]],
  ['add_20to_20recordingobjects_14',['4. Create datasets and add to RecordingObjects',['../workflow.html#create_datasets',1,'']]],
  ['advanced_3a_20recording_20individual_20datasets_15',['Advanced: Recording individual datasets',['../workflow.html#advanced_recording_workflow',1,'']]],
  ['aligned_20timeseries_16',['Use Case: Time-Aligned TimeSeries',['../links.html#link_use_case',1,'']]],
  ['all_20neurodata_5ftypes_17',['Step 3: Create RegisteredType Classes for all neurodata_types',['../integrating_extensions_page.html#labmetadata_extension_registered_type',1,'']]],
  ['an_20existing_20file_20for_20reading_18',['Opening an existing file for reading',['../read_page.html#read_example_open',1,'']]],
  ['an_20nwb_20file_20with_20swmr_20mode_19',['Writing an NWB file with SWMR mode',['../hdf5io.html#hdf5io_swmr_workflow',1,'']]],
  ['and_20add_20to_20recordingobjects_20',['4. Create datasets and add to RecordingObjects',['../workflow.html#create_datasets',1,'']]],
  ['and_20attributes_21',['Reading datasets and attributes',['../read_design_page.html#read_design_sec_read_date',1,'']]],
  ['and_20compression_22',['I/O Filters and Compression',['../hdf5io.html#hdf5io_filters',1,'']]],
  ['and_20finalize_20the_20file_23',['7. Stop the recording and finalize the file.',['../workflow.html#stop_recording',1,'']]],
  ['and_20i_20o_20filters_20in_20aqnwb_24',['Using Chunking and I/O Filters in AqNWB',['../hdf5io.html#hdf5io_filters_usage',1,'']]],
  ['and_20memory_20management_25',['Object and memory management',['../record_design_page.html#record_design_object_memory_management',1,'']]],
  ['and_20processing_20data_26',['Reading and Processing Data',['../read_design_page.html#read_design_example_read',1,'']]],
  ['and_20templated_20child_20class_27',['Using a base class and templated child class',['../registered_type_page.html#implement_templated_registered_type_two_class',1,'']]],
  ['and_20test_28',['Configure, Build and Test',['../dev_install_page.html#configure_build_test',1,'']]],
  ['and_20write_20methods_20for_20datasets_29',['DEFINE_DATASET_FIELD: Creating read and write methods for datasets',['../registered_type_page.html#use_the_define_dataset_field_macro',1,'']]],
  ['and_20writing_20data_30',['Creating and Writing Data',['../read_design_page.html#read_design_example_create',1,'']]],
  ['aqnwb_31',['AqNWB',['../user_demos.html#demos_inspect_electrical_series',1,'Inspect Electrical Series Data using AqNWB'],['../dev_install_page.html#dev_install_aqnwb_sec',1,'Installing AqNWB'],['../user_demos.html#demos_labmetadata_extension',1,'Integrating LabMetaData Extension with AqNWB'],['../hdf5io.html#hdf5io_filters_usage',1,'Using Chunking and I/O Filters in AqNWB']]],
  ['aqnwb_20use_20smwr_20mode_32',['Why does AqNWB use SMWR mode?',['../hdf5io.html#hdf5io_swmr_features',1,'']]],
  ['arbitrary_20fields_33',['Reading arbitrary fields',['../read_page.html#read_example_arbitrary',1,'']]],
  ['attributes_34',['attributes',['../registered_type_page.html#use_the_define_attribute_field_macro',1,'DEFINE_ATTRIBUTE_FIELD: Creating read methods for attributes'],['../read_design_page.html#read_design_sec_read_date',1,'Reading datasets and attributes']]],
  ['automated_20tests_20on_20github_35',['Automated tests on GitHub',['../testing.html#testing_github',1,'']]]
];
