var searchData=
[
  ['read_0',['Implementation of data read',['../read_design_page.html',1,'devdocs']]],
  ['read_20methods_20for_20datasets_20and_20attributes_1',['DEFINE_FIELD: Creating read methods for datasets and attributes',['../registered_type_page.html#use_the_define_field_macro',1,'']]],
  ['read_20methods_20for_20neurodata_5ftype_20objects_2',['DEFINE_REGISTERED_FIELD: Defining read methods for neurodata_type objects',['../registered_type_page.html#use_the_define_registered_field_macro',1,'']]],
  ['read_20methods_20for_20references_20to_20neurodata_5ftype_20objects_3',['DEFINE_REFERENCED_REGISTERED_FIELD: Defining read methods for references to neurodata_type objects',['../registered_type_page.html#use_the_define_referenced_registered_field_macro',1,'']]],
  ['reader_20swmr_20mode_4',['Single-Writer Multiple-Reader (SWMR) Mode',['../hdf5io.html#hdf5io_swmr',1,'']]],
  ['reading_5',['reading',['../read_page.html#read_further_reading',1,'Further reading'],['../read_page.html#read_example_open',1,'Opening an existing file for reading']]],
  ['reading_20and_20processing_20data_6',['Reading and Processing Data',['../read_design_page.html#read_design_example_read',1,'']]],
  ['reading_20arbitrary_20fields_7',['Reading arbitrary fields',['../read_page.html#read_example_arbitrary',1,'']]],
  ['reading_20data_8',['Reading data',['../read_page.html',1,'userdocs']]],
  ['reading_20data_20from_20registeredtype_20objects_9',['Reading data from RegisteredType objects',['../read_page.html#read_example_read',1,'']]],
  ['reading_20datasets_20and_20attributes_10',['Reading datasets and attributes',['../read_design_page.html#read_design_sec_read_date',1,'']]],
  ['reading_20known_20registeredtype_20objects_11',['Reading known RegisteredType objects',['../read_page.html#read_example_predefined_registered_type',1,'']]],
  ['reading_20neurodata_5ftype_20objects_12',['Reading neurodata_type objects',['../read_design_page.html#reading_neurodata_type_objects',1,'']]],
  ['reading_20nwb_20neurodata_5ftypes_13',['Reading NWB neurodata_types',['../read_page.html#read_example_registered_type',1,'']]],
  ['reading_20predefined_20data_20fields_14',['Reading predefined data fields',['../read_page.html#read_design_example_read_posthoc_read_field',1,'']]],
  ['reading_20templated_20registeredtype_20classes_15',['Reading templated RegisteredType classes',['../read_design_page.html#read_design_templates',1,'']]],
  ['reading_20with_20swmr_20mode_16',['Reading with SWMR mode',['../hdf5io.html#hdf5io_swmr_read',1,'']]],
  ['recording_17',['6. Start the recording.',['../workflow.html#start_recording',1,'']]],
  ['recording_20and_20finalize_20the_20file_18',['8. Stop the recording and finalize the file.',['../workflow.html#stop_recording',1,'']]],
  ['recording_20metadata_19',['recording metadata',['../workflow.html#create_recmeta',1,'4. Create the recording metadata'],['../workflow.html#create_recmeta_ecephys',1,'Create the extracellular recording metadata']]],
  ['recording_20workflow_20',['Overview of a recording workflow',['../workflow.html#recording_workflow',1,'']]],
  ['recordingcontainer_20object_21',['2. Create the RecordingContainer object.',['../workflow.html#create_recording_container',1,'']]],
  ['recordingcontainers_22',['5. Create datasets and add to RecordingContainers.',['../workflow.html#create_datasets',1,'']]],
  ['references_20to_20neurodata_5ftype_20objects_23',['DEFINE_REFERENCED_REGISTERED_FIELD: Defining read methods for references to neurodata_type objects',['../registered_type_page.html#use_the_define_referenced_registered_field_macro',1,'']]],
  ['register_5fsubclass_5fwith_5ftypename_24',['Limitations of REGISTER_SUBCLASS_WITH_TYPENAME',['../registered_type_page.html#limitations_registered_subclass_with_typename',1,'']]],
  ['registeredtype_25',['How to Implement a RegisteredType',['../registered_type_page.html#implement_registered_type',1,'']]],
  ['registeredtype_20classes_26',['Templated RegisteredType Classes',['../registered_type_page.html#implement_templated_registered_type',1,'']]],
  ['registeredtype_20classes_27',['Reading templated RegisteredType classes',['../read_design_page.html#read_design_templates',1,'']]],
  ['registeredtype_20classes_20for_20all_20neurodata_5ftypes_28',['Step 3: Create RegisteredType Classes for all neurodata_types',['../integrating_extensions_page.html#labmetadata_extension_registered_type',1,'']]],
  ['registeredtype_20objects_29',['RegisteredType objects',['../read_page.html#read_example_read',1,'Reading data from RegisteredType objects'],['../read_page.html#read_example_predefined_registered_type',1,'Reading known RegisteredType objects'],['../read_page.html#read_example_search',1,'Searching for RegisteredType objects']]],
  ['registeredtype_20registry_30',['How to Use the RegisteredType Registry',['../read_design_page.html#use_registered_type_registry',1,'']]],
  ['registeredtype_20with_20a_20custom_20type_20name_31',['How to implement a RegisteredType with a custom type name',['../registered_type_page.html#using_registered_subclass_with_typename',1,'']]],
  ['registeredtype_20works_32',['How the Type Registry in RegisteredType Works',['../read_design_page.html#type_registry',1,'']]],
  ['registeredtypes_33',['Testing RegisteredTypes',['../registered_type_page.html#implement_registered_type_unit_tests',1,'']]],
  ['registering_20a_20namespace_34',['Registering a Namespace',['../integrating_extensions_page.html#register_namespace',1,'']]],
  ['registry_35',['How to Use the RegisteredType Registry',['../read_design_page.html#use_registered_type_registry',1,'']]],
  ['registry_36',['Example: Using the type registry',['../read_design_page.html#use_registered_type_registry_example',1,'']]],
  ['registry_20in_20registeredtype_20works_37',['How the Type Registry in RegisteredType Works',['../read_design_page.html#type_registry',1,'']]],
  ['requirements_38',['Requirements',['../dev_install_page.html#dev_requirements_sec',1,'Requirements'],['../user_install_page.html#user_requirements_sec',1,'Requirements']]],
  ['running_20unit_20tests_39',['Running Unit Tests',['../testing.html#testing_unit_run',1,'']]]
];
