var searchData=
[
  ['i_20o_0',['HDF5 I/O',['../hdf5io.html',1,'userdocs']]],
  ['i_20o_20filters_20and_20compression_1',['I/O Filters and Compression',['../hdf5io.html#hdf5io_filters',1,'']]],
  ['i_20o_20filters_20in_20aqnwb_2',['Using Chunking and I/O Filters in AqNWB',['../hdf5io.html#hdf5io_filters_usage',1,'']]],
  ['i_20o_20object_3',['1. Create the I/O object.',['../workflow.html#create_io',1,'']]],
  ['implement_20a_20registeredtype_4',['How to Implement a RegisteredType',['../registered_type_page.html#implement_registered_type',1,'']]],
  ['implement_20a_20registeredtype_20with_20a_20custom_20type_20name_5',['How to implement a RegisteredType with a custom type name',['../registered_type_page.html#using_registered_subclass_with_typename',1,'']]],
  ['implementation_20details_6',['Example Implementation Details',['../read_design_page.html#read_design_example',1,'']]],
  ['implementation_20of_20data_20read_7',['Implementation of data read',['../read_design_page.html',1,'devdocs']]],
  ['implementing_20a_20new_20neurodata_20type_8',['Implementing a new Neurodata Type',['../registered_type_page.html',1,'devdocs']]],
  ['implementing_20a_20new_20type_9',['Example: Implementing a new type',['../registered_type_page.html#implement_registered_type_example',1,'']]],
  ['in_20aqnwb_10',['Using Chunking and I/O Filters in AqNWB',['../hdf5io.html#hdf5io_filters_usage',1,'']]],
  ['in_20doxygen_11',['Including Code Examples in Doxygen',['../dev_docs_page.html#dev_docs_codeexamples_incl_sec',1,'']]],
  ['in_20registeredtype_20works_12',['How the Type Registry in RegisteredType Works',['../read_design_page.html#type_registry',1,'']]],
  ['including_20code_20examples_20in_20doxygen_13',['Including Code Examples in Doxygen',['../dev_docs_page.html#dev_docs_codeexamples_incl_sec',1,'']]],
  ['inspect_20electrical_20series_20data_20using_20aqnwb_14',['Inspect Electrical Series Data using AqNWB',['../user_demos.html#demos_inspect_electrical_series',1,'']]],
  ['install_15',['Install',['../user_install_page.html#userbuild_install_sec',1,'']]],
  ['installation_16',['Installation',['../index.html#mainpage_installation',1,'']]],
  ['installation_20setup_17',['Installation &amp;amp; Setup',['../dev_install_page.html',1,'devdocs']]],
  ['installing_20aqnwb_18',['Installing AqNWB',['../user_install_page.html',1,'userdocs']]],
  ['integrate_20a_20new_20namespace_19',['How to Integrate a New Namespace',['../integrating_extensions_page.html#integrate_namespace',1,'']]],
  ['integrating_20labmetadata_20extension_20with_20aqnwb_20',['Integrating LabMetaData Extension with AqNWB',['../user_demos.html#demos_labmetadata_extension',1,'']]],
  ['integrating_20nwb_20extensions_21',['Integrating NWB Extensions',['../integrating_extensions_page.html',1,'devdocs']]]
];
