var searchData=
[
  ['c_0',['Step 2: Convert the Schema to C++',['../integrating_extensions_page.html#labmetadata_extension_cpp_generation',1,'']]],
  ['c_20standard_20version_1',['Selecting a newer C++ standard version',['../dev_install_page.html#devbuild_cpp_std_sec',1,'']]],
  ['case_3a_20time_20aligned_20timeseries_2',['Use Case: Time-Aligned TimeSeries',['../links.html#link_use_case',1,'']]],
  ['changelog_20⚖️_3',['Changelog ⚖️',['../changelog_page.html',1,'devdocs']]],
  ['changes_4',['3. Commit and Push Changes',['../release_workflow.html#release_steps_3',1,'']]],
  ['channels_20at_20once_20interleaved_20data_5',['Writing all channels at once (interleaved data)',['../workflow.html#write_data_allchannels',1,'']]],
  ['checklist_6',['Quick Checklist',['../release_workflow.html#quick_checklist',1,'']]],
  ['child_20class_7',['Using a base class and templated child class',['../registered_type_page.html#implement_templated_registered_type_two_class',1,'']]],
  ['chunking_8',['Chunking',['../hdf5io.html#hdf5io_chunking',1,'']]],
  ['chunking_20and_20i_20o_20filters_20in_20aqnwb_9',['Using Chunking and I/O Filters in AqNWB',['../hdf5io.html#hdf5io_filters_usage',1,'']]],
  ['class_10',['class',['../registered_type_page.html#implement_templated_registered_type_two_class',1,'Using a base class and templated child class'],['../registered_type_page.html#implement_templated_registered_type_single_class',1,'Using a single templated class']]],
  ['class_20and_20templated_20child_20class_11',['Using a base class and templated child class',['../registered_type_page.html#implement_templated_registered_type_two_class',1,'']]],
  ['classes_12',['Templated RegisteredType Classes',['../registered_type_page.html#implement_templated_registered_type',1,'']]],
  ['classes_13',['Reading templated RegisteredType classes',['../read_design_page.html#read_design_templates',1,'']]],
  ['classes_20for_20all_20neurodata_5ftypes_14',['Step 3: Create RegisteredType Classes for all neurodata_types',['../integrating_extensions_page.html#labmetadata_extension_registered_type',1,'']]],
  ['cleanup_15',['6. Cleanup',['../links.html#link_cleanup',1,'']]],
  ['code_16',['Code',['../dev_docs_page.html#dev_docs_codeexamples_def_sec',1,'Creating the Example Code'],['../dev_docs_page.html#dev_docs_codeexamples_run_sec',1,'Testing the Example Code']]],
  ['code_20examples_17',['Code Examples',['../hdf5io.html#hdf5io_swmr_examples',1,'Code Examples'],['../dev_docs_page.html#dev_docs_codeexamples_sec',1,'Creating Code Examples']]],
  ['code_20examples_20in_20doxygen_18',['Including Code Examples in Doxygen',['../dev_docs_page.html#dev_docs_codeexamples_incl_sec',1,'']]],
  ['code_20of_20conduct_19',['Code of Conduct',['../legal_page.html#legal_code_of_conduct',1,'']]],
  ['coded_20column_20',['Setup: create the EventsTable with a coded column',['../events.html#events_meanings_setup',1,'']]],
  ['collections_21',['RecordingObjects for Managing Collections',['../record_design_page.html#record_design_sec_recording_containers',1,'']]],
  ['column_22',['Setup: create the EventsTable with a coded column',['../events.html#events_meanings_setup',1,'']]],
  ['column_20based_20bulk_20acquisition_23',['Column based bulk acquisition',['../events.html#events_colbased',1,'Pattern 2: Column-based (bulk) acquisition'],['../time_intervals.html#time_intervals_colbased',1,'Pattern 2: Column-based (bulk) acquisition']]],
  ['columns_24',['columns',['../events.html#events_colbased_adddata',1,'Add data to columns'],['../time_intervals.html#time_intervals_colbased_adddata',1,'Add data to columns']]],
  ['columns_20with_20a_20meaningstable_25',['Annotating columns with a MeaningsTable',['../events.html#events_meanings',1,'']]],
  ['command_26',['Using the generate-types command',['../registered_type_page.html#using_schematype_to_aqnwb',1,'']]],
  ['commit_20and_20push_20changes_27',['3. Commit and Push Changes',['../release_workflow.html#release_steps_3',1,'']]],
  ['compression_28',['I/O Filters and Compression',['../hdf5io.html#hdf5io_filters',1,'']]],
  ['conduct_29',['Code of Conduct',['../legal_page.html#legal_code_of_conduct',1,'']]],
  ['configure_20and_20create_20the_20eventstable_30',['3. Configure and create the EventsTable',['../events.html#events_configure_table',1,'']]],
  ['configure_20and_20create_20the_20timeintervals_20table_31',['3. Configure and create the TimeIntervals table',['../time_intervals.html#time_intervals_configure_table',1,'']]],
  ['configure_20build_20and_20test_32',['Configure, Build and Test',['../dev_install_page.html#configure_build_test',1,'']]],
  ['consistent_20recording_33',['TimeSeries Convenience Methods for Consistent Recording',['../record_design_page.html#record_design_sec_timeseries',1,'']]],
  ['convenience_20methods_20for_20consistent_20recording_34',['TimeSeries Convenience Methods for Consistent Recording',['../record_design_page.html#record_design_sec_timeseries',1,'']]],
  ['convenience_20utilities_35',['NWB I/O convenience utilities',['../record_design_page.html#record_design_nwbio_utils',1,'']]],
  ['convert_20the_20schema_20to_20c_36',['Step 2: Convert the Schema to C++',['../integrating_extensions_page.html#labmetadata_extension_cpp_generation',1,'']]],
  ['copyright_37',['Copyright',['../legal_page.html#legal_copyright',1,'']]],
  ['cppcheck_38',['Static Analysis (Cppcheck)',['../testing.html#testing_cppcheck',1,'']]],
  ['cppcheck_20on_20github_39',['Cppcheck on GitHub',['../testing.html#testing_cppcheck_github',1,'']]],
  ['create_20a_20processingmodule_40',['3. Create a ProcessingModule',['../links.html#link_processing',1,'']]],
  ['create_20a_20release_20branch_41',['1. Create a Release Branch',['../release_workflow.html#release_steps_1',1,'']]],
  ['create_20datasets_20and_20add_20to_20recordingobjects_42',['4. Create datasets and add to RecordingObjects',['../workflow.html#create_datasets',1,'']]],
  ['create_20registeredtype_20classes_20for_20all_20neurodata_5ftypes_43',['Step 3: Create RegisteredType Classes for all neurodata_types',['../integrating_extensions_page.html#labmetadata_extension_registered_type',1,'']]],
  ['create_20the_20eventstable_44',['3. Configure and create the EventsTable',['../events.html#events_configure_table',1,'']]],
  ['create_20the_20eventstable_20with_20a_20coded_20column_45',['Setup: create the EventsTable with a coded column',['../events.html#events_meanings_setup',1,'']]],
  ['create_20the_20extracellular_20recording_20metadata_46',['Create the extracellular recording metadata',['../workflow.html#create_recmeta_ecephys',1,'']]],
  ['create_20the_20i_20o_20object_47',['Create the I O object',['../events.html#events_io',1,'1. Create the I/O object'],['../time_intervals.html#time_intervals_io',1,'1. Create the I/O object'],['../workflow.html#create_io',1,'1. Create the I/O object']]],
  ['create_20the_20linked_20timeseries_48',['4. Create the Linked TimeSeries',['../links.html#link_linked',1,'']]],
  ['create_20the_20meaningstable_49',['Create the MeaningsTable',['../events.html#events_meanings_create',1,'']]],
  ['create_20the_20nwbfile_50',['Create the NWBFile',['../events.html#events_nwbfile',1,'2. Create the NWBFile'],['../time_intervals.html#time_intervals_nwbfile',1,'2. Create the NWBFile'],['../workflow.html#create_nwbfile',1,'2. Create the NWBFile']]],
  ['create_20the_20original_20timeseries_51',['2. Create the Original TimeSeries',['../links.html#link_original',1,'']]],
  ['create_20the_20recording_20metadata_52',['3. Create the recording metadata',['../workflow.html#create_recmeta',1,'']]],
  ['create_20the_20timeintervals_20table_53',['3. Configure and create the TimeIntervals table',['../time_intervals.html#time_intervals_configure_table',1,'']]],
  ['creating_20and_20writing_20data_54',['Creating and Writing Data',['../read_design_page.html#read_design_example_create',1,'']]],
  ['creating_20code_20examples_55',['Creating Code Examples',['../dev_docs_page.html#dev_docs_codeexamples_sec',1,'']]],
  ['creating_20custom_20dot_20graphs_56',['Creating Custom Dot Graphs',['../dev_docs_page.html#dev_docs_graphviz_sec',1,'']]],
  ['creating_20new_20documentation_20pages_57',['Creating New Documentation Pages',['../dev_docs_page.html#dev_docs_creating',1,'']]],
  ['creating_20read_20and_20write_20methods_20for_20datasets_58',['DEFINE_DATASET_FIELD: Creating read and write methods for datasets',['../registered_type_page.html#use_the_define_dataset_field_macro',1,'']]],
  ['creating_20read_20methods_20for_20attributes_59',['DEFINE_ATTRIBUTE_FIELD: Creating read methods for attributes',['../registered_type_page.html#use_the_define_attribute_field_macro',1,'']]],
  ['creating_20the_20example_20code_60',['Creating the Example Code',['../dev_docs_page.html#dev_docs_codeexamples_def_sec',1,'']]],
  ['creation_61',['creation',['../events.html#events_setup',1,'Setup: I/O, NWBFile, and table creation'],['../time_intervals.html#time_intervals_setup',1,'Setup: I/O, NWBFile, and table creation']]],
  ['custom_20dot_20graphs_62',['Creating Custom Dot Graphs',['../dev_docs_page.html#dev_docs_graphviz_sec',1,'']]],
  ['custom_20hdf5_20installation_63',['Using a custom HDF5 installation',['../dev_install_page.html#devbuild_custom_hdf5_sec',1,'']]],
  ['custom_20type_20name_64',['How to implement a RegisteredType with a custom type name',['../registered_type_page.html#using_registered_subclass_with_typename',1,'']]]
];
