#include "NWBData.hpp"

#include "Utils.hpp"

using namespace AQNWB::NWB;
using namespace AQNWB::IO;

// Initialize the static registered_ member to trigger registration
REGISTER_SUBCLASS_IMPL(NWBData)

NWBData::NWBData(const std::string& path, std::shared_ptr<AQNWB::IO::BaseIO> io)
    : Data(path, io)
{
}

Status NWBData::initialize(const AQNWB::IO::ArrayDataSetConfig& dataConfig)
{
  return Data::initialize(dataConfig);
}

namespace AQNWB::NWB
{
// Explicitly instantiate the NWBDataTyped template for all common data types.
// This ensures that these specializations are generated by the compiler,
// reducing compile times and ensuring availability throughout the program.
template class NWBDataTyped<uint8_t>;
template class NWBDataTyped<uint16_t>;
template class NWBDataTyped<uint32_t>;
template class NWBDataTyped<uint64_t>;
template class NWBDataTyped<int8_t>;
template class NWBDataTyped<int16_t>;
template class NWBDataTyped<int32_t>;
template class NWBDataTyped<int64_t>;
template class NWBDataTyped<float>;
template class NWBDataTyped<double>;
template class NWBDataTyped<std::string>;
}  // namespace AQNWB::NWB
