add_test( [==[Test ArrayDataSetConfig]==] /home/runner/work/aqnwb/aqnwb/build2/tests/aqnwb_test [==[Test ArrayDataSetConfig]==]  )
set_tests_properties( [==[Test ArrayDataSetConfig]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/aqnwb/aqnwb/build2/tests)
add_test( [==[BaseDataType equality operator]==] /home/runner/work/aqnwb/aqnwb/build2/tests/aqnwb_test [==[BaseDataType equality operator]==]  )
set_tests_properties( [==[BaseDataType equality operator]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/aqnwb/aqnwb/build2/tests)
add_test( [==[BaseDataType fromTypeId]==] /home/runner/work/aqnwb/aqnwb/build2/tests/aqnwb_test [==[BaseDataType fromTypeId]==]  )
set_tests_properties( [==[BaseDataType fromTypeId]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/aqnwb/aqnwb/build2/tests)
add_test( [==[Test findTypes and getFullTypeName]==] /home/runner/work/aqnwb/aqnwb/build2/tests/aqnwb_test [==[Test findTypes and getFullTypeName]==]  )
set_tests_properties( [==[Test findTypes and getFullTypeName]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/aqnwb/aqnwb/build2/tests)
add_test( [==[Test BaseArrayDataSetConfig polymorphism]==] /home/runner/work/aqnwb/aqnwb/build2/tests/aqnwb_test [==[Test BaseArrayDataSetConfig polymorphism]==]  )
set_tests_properties( [==[Test BaseArrayDataSetConfig polymorphism]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/aqnwb/aqnwb/build2/tests)
add_test( [==[Test LinkArrayDataSetConfig]==] /home/runner/work/aqnwb/aqnwb/build2/tests/aqnwb_test [==[Test LinkArrayDataSetConfig]==]  )
set_tests_properties( [==[Test LinkArrayDataSetConfig]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/aqnwb/aqnwb/build2/tests)
add_test( [==[Test LinkArrayDataSetConfig::validateTarget]==] /home/runner/work/aqnwb/aqnwb/build2/tests/aqnwb_test [==[Test LinkArrayDataSetConfig::validateTarget]==]  )
set_tests_properties( [==[Test LinkArrayDataSetConfig::validateTarget]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/aqnwb/aqnwb/build2/tests)
add_test( [==[Test Channel Construction and Basic Operations]==] /home/runner/work/aqnwb/aqnwb/build2/tests/aqnwb_test [==[Test Channel Construction and Basic Operations]==]  )
set_tests_properties( [==[Test Channel Construction and Basic Operations]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/aqnwb/aqnwb/build2/tests)
add_test( [==[Test Channel Setters]==] /home/runner/work/aqnwb/aqnwb/build2/tests/aqnwb_test [==[Test Channel Setters]==]  )
set_tests_properties( [==[Test Channel Setters]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/aqnwb/aqnwb/build2/tests)
add_test( [==[Test Channel Copy and Move Operations]==] /home/runner/work/aqnwb/aqnwb/build2/tests/aqnwb_test [==[Test Channel Copy and Move Operations]==]  )
set_tests_properties( [==[Test Channel Copy and Move Operations]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/aqnwb/aqnwb/build2/tests)
add_test( Data /home/runner/work/aqnwb/aqnwb/build2/tests/aqnwb_test Data  )
set_tests_properties( Data PROPERTIES WORKING_DIRECTORY /home/runner/work/aqnwb/aqnwb/build2/tests)
add_test( DataTyped /home/runner/work/aqnwb/aqnwb/build2/tests/aqnwb_test DataTyped  )
set_tests_properties( DataTyped PROPERTIES WORKING_DIRECTORY /home/runner/work/aqnwb/aqnwb/build2/tests)
add_test( Device /home/runner/work/aqnwb/aqnwb/build2/tests/aqnwb_test Device  )
set_tests_properties( Device PROPERTIES WORKING_DIRECTORY /home/runner/work/aqnwb/aqnwb/build2/tests)
add_test( DynamicTable /home/runner/work/aqnwb/aqnwb/build2/tests/aqnwb_test DynamicTable  )
set_tests_properties( DynamicTable PROPERTIES WORKING_DIRECTORY /home/runner/work/aqnwb/aqnwb/build2/tests)
add_test( [==[registered ecephys types]==] /home/runner/work/aqnwb/aqnwb/build2/tests/aqnwb_test [==[registered ecephys types]==]  )
set_tests_properties( [==[registered ecephys types]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/aqnwb/aqnwb/build2/tests)
add_test( ElectricalSeries /home/runner/work/aqnwb/aqnwb/build2/tests/aqnwb_test ElectricalSeries  )
set_tests_properties( ElectricalSeries PROPERTIES WORKING_DIRECTORY /home/runner/work/aqnwb/aqnwb/build2/tests)
add_test( SpikeEventSeries /home/runner/work/aqnwb/aqnwb/build2/tests/aqnwb_test SpikeEventSeries  )
set_tests_properties( SpikeEventSeries PROPERTIES WORKING_DIRECTORY /home/runner/work/aqnwb/aqnwb/build2/tests)
add_test( ElementIdentifiers /home/runner/work/aqnwb/aqnwb/build2/tests/aqnwb_test ElementIdentifiers  )
set_tests_properties( ElementIdentifiers PROPERTIES WORKING_DIRECTORY /home/runner/work/aqnwb/aqnwb/build2/tests)
add_test( ElectrodesTable /home/runner/work/aqnwb/aqnwb/build2/tests/aqnwb_test ElectrodesTable  )
set_tests_properties( ElectrodesTable PROPERTIES WORKING_DIRECTORY /home/runner/work/aqnwb/aqnwb/build2/tests)
add_test( [==[open - hdf5 file modes]==] /home/runner/work/aqnwb/aqnwb/build2/tests/aqnwb_test [==[open - hdf5 file modes]==]  )
set_tests_properties( [==[open - hdf5 file modes]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/aqnwb/aqnwb/build2/tests)
add_test( createGroup /home/runner/work/aqnwb/aqnwb/build2/tests/aqnwb_test createGroup  )
set_tests_properties( createGroup PROPERTIES WORKING_DIRECTORY /home/runner/work/aqnwb/aqnwb/build2/tests)
add_test( getStorageObjects /home/runner/work/aqnwb/aqnwb/build2/tests/aqnwb_test getStorageObjects  )
set_tests_properties( getStorageObjects PROPERTIES WORKING_DIRECTORY /home/runner/work/aqnwb/aqnwb/build2/tests)
add_test( getStorageObjectShape /home/runner/work/aqnwb/aqnwb/build2/tests/aqnwb_test getStorageObjectShape  )
set_tests_properties( getStorageObjectShape PROPERTIES WORKING_DIRECTORY /home/runner/work/aqnwb/aqnwb/build2/tests)
add_test( [==[HDF5IO; write datasets]==] /home/runner/work/aqnwb/aqnwb/build2/tests/aqnwb_test [==[HDF5IO; write datasets]==]  )
set_tests_properties( [==[HDF5IO; write datasets]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/aqnwb/aqnwb/build2/tests)
add_test( [==[HDF5IO createArrayDataSet with filters]==] /home/runner/work/aqnwb/aqnwb/build2/tests/aqnwb_test [==[HDF5IO createArrayDataSet with filters]==]  )
set_tests_properties( [==[HDF5IO createArrayDataSet with filters]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/aqnwb/aqnwb/build2/tests)
add_test( [==[HDF5IO; create attributes]==] /home/runner/work/aqnwb/aqnwb/build2/tests/aqnwb_test [==[HDF5IO; create attributes]==]  )
set_tests_properties( [==[HDF5IO; create attributes]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/aqnwb/aqnwb/build2/tests)
add_test( [==[HDF5IO; SWMR mode]==] /home/runner/work/aqnwb/aqnwb/build2/tests/aqnwb_test [==[HDF5IO; SWMR mode]==]  )
set_tests_properties( [==[HDF5IO; SWMR mode]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/aqnwb/aqnwb/build2/tests)
add_test( getH5ObjectType /home/runner/work/aqnwb/aqnwb/build2/tests/aqnwb_test getH5ObjectType  )
set_tests_properties( getH5ObjectType PROPERTIES WORKING_DIRECTORY /home/runner/work/aqnwb/aqnwb/build2/tests)
add_test( getNativeType /home/runner/work/aqnwb/aqnwb/build2/tests/aqnwb_test getNativeType  )
set_tests_properties( getNativeType PROPERTIES WORKING_DIRECTORY /home/runner/work/aqnwb/aqnwb/build2/tests)
add_test( getH5Type /home/runner/work/aqnwb/aqnwb/build2/tests/aqnwb_test getH5Type  )
set_tests_properties( getH5Type PROPERTIES WORKING_DIRECTORY /home/runner/work/aqnwb/aqnwb/build2/tests)
add_test( objectExists /home/runner/work/aqnwb/aqnwb/build2/tests/aqnwb_test objectExists  )
set_tests_properties( objectExists PROPERTIES WORKING_DIRECTORY /home/runner/work/aqnwb/aqnwb/build2/tests)
add_test( HDF5IOI::attributeExists /home/runner/work/aqnwb/aqnwb/build2/tests/aqnwb_test HDF5IOI::attributeExists  )
set_tests_properties( HDF5IOI::attributeExists PROPERTIES WORKING_DIRECTORY /home/runner/work/aqnwb/aqnwb/build2/tests)
add_test( getStorageObjectType /home/runner/work/aqnwb/aqnwb/build2/tests/aqnwb_test getStorageObjectType  )
set_tests_properties( getStorageObjectType PROPERTIES WORKING_DIRECTORY /home/runner/work/aqnwb/aqnwb/build2/tests)
add_test( readAttribute /home/runner/work/aqnwb/aqnwb/build2/tests/aqnwb_test readAttribute  )
set_tests_properties( readAttribute PROPERTIES WORKING_DIRECTORY /home/runner/work/aqnwb/aqnwb/build2/tests)
add_test( [==[HDF5IO; read dataset]==] /home/runner/work/aqnwb/aqnwb/build2/tests/aqnwb_test [==[HDF5IO; read dataset]==]  )
set_tests_properties( [==[HDF5IO; read dataset]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/aqnwb/aqnwb/build2/tests)
add_test( [==[HDF5IO; read dataset subset]==] /home/runner/work/aqnwb/aqnwb/build2/tests/aqnwb_test [==[HDF5IO; read dataset subset]==]  )
set_tests_properties( [==[HDF5IO; read dataset subset]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/aqnwb/aqnwb/build2/tests)
add_test( [==[Test HDF5IO createArrayDataSet with LinkArrayDataSetConfig]==] /home/runner/work/aqnwb/aqnwb/build2/tests/aqnwb_test [==[Test HDF5IO createArrayDataSet with LinkArrayDataSetConfig]==]  )
set_tests_properties( [==[Test HDF5IO createArrayDataSet with LinkArrayDataSetConfig]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/aqnwb/aqnwb/build2/tests)
add_test( getStorageObjectDataType /home/runner/work/aqnwb/aqnwb/build2/tests/aqnwb_test getStorageObjectDataType  )
set_tests_properties( getStorageObjectDataType PROPERTIES WORKING_DIRECTORY /home/runner/work/aqnwb/aqnwb/build2/tests)
add_test( [==[HDF5FilterConfig constructor]==] /home/runner/work/aqnwb/aqnwb/build2/tests/aqnwb_test [==[HDF5FilterConfig constructor]==]  )
set_tests_properties( [==[HDF5FilterConfig constructor]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/aqnwb/aqnwb/build2/tests)
add_test( [==[HDF5FilterConfig factory methods]==] /home/runner/work/aqnwb/aqnwb/build2/tests/aqnwb_test [==[HDF5FilterConfig factory methods]==]  )
set_tests_properties( [==[HDF5FilterConfig factory methods]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/aqnwb/aqnwb/build2/tests)
add_test( [==[HDF5ArrayDataSetConfig addFilter]==] /home/runner/work/aqnwb/aqnwb/build2/tests/aqnwb_test [==[HDF5ArrayDataSetConfig addFilter]==]  )
set_tests_properties( [==[HDF5ArrayDataSetConfig addFilter]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/aqnwb/aqnwb/build2/tests)
add_test( [==[HDF5RecordingData basic operations]==] /home/runner/work/aqnwb/aqnwb/build2/tests/aqnwb_test [==[HDF5RecordingData basic operations]==]  )
set_tests_properties( [==[HDF5RecordingData basic operations]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/aqnwb/aqnwb/build2/tests)
add_test( [==[HDF5RecordingData write operations]==] /home/runner/work/aqnwb/aqnwb/build2/tests/aqnwb_test [==[HDF5RecordingData write operations]==]  )
set_tests_properties( [==[HDF5RecordingData write operations]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/aqnwb/aqnwb/build2/tests)
add_test( [==[HDF5RecordingData multi-dimensional operations]==] /home/runner/work/aqnwb/aqnwb/build2/tests/aqnwb_test [==[HDF5RecordingData multi-dimensional operations]==]  )
set_tests_properties( [==[HDF5RecordingData multi-dimensional operations]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/aqnwb/aqnwb/build2/tests)
add_test( AnnotationSeries /home/runner/work/aqnwb/aqnwb/build2/tests/aqnwb_test AnnotationSeries  )
set_tests_properties( AnnotationSeries PROPERTIES WORKING_DIRECTORY /home/runner/work/aqnwb/aqnwb/build2/tests)
add_test( [==[Test NamespaceRegistry]==] /home/runner/work/aqnwb/aqnwb/build2/tests/aqnwb_test [==[Test NamespaceRegistry]==]  )
set_tests_properties( [==[Test NamespaceRegistry]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/aqnwb/aqnwb/build2/tests)
add_test( [==[NWBFile registered]==] /home/runner/work/aqnwb/aqnwb/build2/tests/aqnwb_test [==[NWBFile registered]==]  )
set_tests_properties( [==[NWBFile registered]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/aqnwb/aqnwb/build2/tests)
add_test( saveNWBFile /home/runner/work/aqnwb/aqnwb/build2/tests/aqnwb_test saveNWBFile  )
set_tests_properties( saveNWBFile PROPERTIES WORKING_DIRECTORY /home/runner/work/aqnwb/aqnwb/build2/tests)
add_test( initialize /home/runner/work/aqnwb/aqnwb/build2/tests/aqnwb_test initialize  )
set_tests_properties( initialize PROPERTIES WORKING_DIRECTORY /home/runner/work/aqnwb/aqnwb/build2/tests)
add_test( createElectrodesTable /home/runner/work/aqnwb/aqnwb/build2/tests/aqnwb_test createElectrodesTable  )
set_tests_properties( createElectrodesTable PROPERTIES WORKING_DIRECTORY /home/runner/work/aqnwb/aqnwb/build2/tests)
add_test( createElectricalSeriesWithSubsetOfElectrodes /home/runner/work/aqnwb/aqnwb/build2/tests/aqnwb_test createElectricalSeriesWithSubsetOfElectrodes  )
set_tests_properties( createElectricalSeriesWithSubsetOfElectrodes PROPERTIES WORKING_DIRECTORY /home/runner/work/aqnwb/aqnwb/build2/tests)
add_test( createElectricalSeriesFailsWithoutElectrodesTable /home/runner/work/aqnwb/aqnwb/build2/tests/aqnwb_test createElectricalSeriesFailsWithoutElectrodesTable  )
set_tests_properties( createElectricalSeriesFailsWithoutElectrodesTable PROPERTIES WORKING_DIRECTORY /home/runner/work/aqnwb/aqnwb/build2/tests)
add_test( createElectricalSeriesFailsWithOutOfRangeIndices /home/runner/work/aqnwb/aqnwb/build2/tests/aqnwb_test createElectricalSeriesFailsWithOutOfRangeIndices  )
set_tests_properties( createElectricalSeriesFailsWithOutOfRangeIndices PROPERTIES WORKING_DIRECTORY /home/runner/work/aqnwb/aqnwb/build2/tests)
add_test( createElectricalSeries /home/runner/work/aqnwb/aqnwb/build2/tests/aqnwb_test createElectricalSeries  )
set_tests_properties( createElectricalSeries PROPERTIES WORKING_DIRECTORY /home/runner/work/aqnwb/aqnwb/build2/tests)
add_test( createMultipleEcephysDatasets /home/runner/work/aqnwb/aqnwb/build2/tests/aqnwb_test createMultipleEcephysDatasets  )
set_tests_properties( createMultipleEcephysDatasets PROPERTIES WORKING_DIRECTORY /home/runner/work/aqnwb/aqnwb/build2/tests)
add_test( createAnnotationSeries /home/runner/work/aqnwb/aqnwb/build2/tests/aqnwb_test createAnnotationSeries  )
set_tests_properties( createAnnotationSeries PROPERTIES WORKING_DIRECTORY /home/runner/work/aqnwb/aqnwb/build2/tests)
add_test( setCanModifyObjectsMode /home/runner/work/aqnwb/aqnwb/build2/tests/aqnwb_test setCanModifyObjectsMode  )
set_tests_properties( setCanModifyObjectsMode PROPERTIES WORKING_DIRECTORY /home/runner/work/aqnwb/aqnwb/build2/tests)
add_test( testAttributeAndDatasetFields /home/runner/work/aqnwb/aqnwb/build2/tests/aqnwb_test testAttributeAndDatasetFields  )
set_tests_properties( testAttributeAndDatasetFields PROPERTIES WORKING_DIRECTORY /home/runner/work/aqnwb/aqnwb/build2/tests)
add_test( [==[ProcessingModule registered]==] /home/runner/work/aqnwb/aqnwb/build2/tests/aqnwb_test [==[ProcessingModule registered]==]  )
set_tests_properties( [==[ProcessingModule registered]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/aqnwb/aqnwb/build2/tests)
add_test( createProcessingModule /home/runner/work/aqnwb/aqnwb/build2/tests/aqnwb_test createProcessingModule  )
set_tests_properties( createProcessingModule PROPERTIES WORKING_DIRECTORY /home/runner/work/aqnwb/aqnwb/build2/tests)
add_test( createMultipleProcessingModules /home/runner/work/aqnwb/aqnwb/build2/tests/aqnwb_test createMultipleProcessingModules  )
set_tests_properties( createMultipleProcessingModules PROPERTIES WORKING_DIRECTORY /home/runner/work/aqnwb/aqnwb/build2/tests)
add_test( [==[ProcessingModule createNWBDataInterface and readNWBDataInterface]==] /home/runner/work/aqnwb/aqnwb/build2/tests/aqnwb_test [==[ProcessingModule createNWBDataInterface and readNWBDataInterface]==]  )
set_tests_properties( [==[ProcessingModule createNWBDataInterface and readNWBDataInterface]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/aqnwb/aqnwb/build2/tests)
add_test( [==[ProcessingModule createDynamicTable and readDynamicTable]==] /home/runner/work/aqnwb/aqnwb/build2/tests/aqnwb_test [==[ProcessingModule createDynamicTable and readDynamicTable]==]  )
set_tests_properties( [==[ProcessingModule createDynamicTable and readDynamicTable]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/aqnwb/aqnwb/build2/tests)
add_test( [==[ProcessingModule initialize fails when IO is deleted]==] /home/runner/work/aqnwb/aqnwb/build2/tests/aqnwb_test [==[ProcessingModule initialize fails when IO is deleted]==]  )
set_tests_properties( [==[ProcessingModule initialize fails when IO is deleted]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/aqnwb/aqnwb/build2/tests)
add_test( [==[DataBlock - Basic Functionality]==] /home/runner/work/aqnwb/aqnwb/build2/tests/aqnwb_test [==[DataBlock - Basic Functionality]==]  )
set_tests_properties( [==[DataBlock - Basic Functionality]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/aqnwb/aqnwb/build2/tests)
add_test( [==[DataBlockGeneric - Basic Functionality]==] /home/runner/work/aqnwb/aqnwb/build2/tests/aqnwb_test [==[DataBlockGeneric - Basic Functionality]==]  )
set_tests_properties( [==[DataBlockGeneric - Basic Functionality]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/aqnwb/aqnwb/build2/tests)
add_test( [==[DataBlock - Edge Cases]==] /home/runner/work/aqnwb/aqnwb/build2/tests/aqnwb_test [==[DataBlock - Edge Cases]==]  )
set_tests_properties( [==[DataBlock - Edge Cases]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/aqnwb/aqnwb/build2/tests)
add_test( [==[DataBlockGeneric - as_variant Method]==] /home/runner/work/aqnwb/aqnwb/build2/tests/aqnwb_test [==[DataBlockGeneric - as_variant Method]==]  )
set_tests_properties( [==[DataBlockGeneric - as_variant Method]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/aqnwb/aqnwb/build2/tests)
add_test( [==[DataBlockGeneric - Compute Mean with std::visit]==] /home/runner/work/aqnwb/aqnwb/build2/tests/aqnwb_test [==[DataBlockGeneric - Compute Mean with std::visit]==]  )
set_tests_properties( [==[DataBlockGeneric - Compute Mean with std::visit]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/aqnwb/aqnwb/build2/tests)
add_test( [==[ConstMultiArrayView - Basic Functionality]==] /home/runner/work/aqnwb/aqnwb/build2/tests/aqnwb_test [==[ConstMultiArrayView - Basic Functionality]==]  )
set_tests_properties( [==[ConstMultiArrayView - Basic Functionality]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/aqnwb/aqnwb/build2/tests)
add_test( [==[DataBlock - as_multi_array]==] /home/runner/work/aqnwb/aqnwb/build2/tests/aqnwb_test [==[DataBlock - as_multi_array]==]  )
set_tests_properties( [==[DataBlock - as_multi_array]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/aqnwb/aqnwb/build2/tests)
add_test( [==[ReadDataWrapper; introspection methods]==] /home/runner/work/aqnwb/aqnwb/build2/tests/aqnwb_test [==[ReadDataWrapper; introspection methods]==]  )
set_tests_properties( [==[ReadDataWrapper; introspection methods]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/aqnwb/aqnwb/build2/tests)
add_test( writeContinuousData /home/runner/work/aqnwb/aqnwb/build2/tests/aqnwb_test writeContinuousData  )
set_tests_properties( writeContinuousData PROPERTIES WORKING_DIRECTORY /home/runner/work/aqnwb/aqnwb/build2/tests)
add_test( [==[RecordingObjects recording workflow tests]==] /home/runner/work/aqnwb/aqnwb/build2/tests/aqnwb_test [==[RecordingObjects recording workflow tests]==]  )
set_tests_properties( [==[RecordingObjects recording workflow tests]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/aqnwb/aqnwb/build2/tests)
add_test( RegisterType /home/runner/work/aqnwb/aqnwb/build2/tests/aqnwb_test RegisterType  )
set_tests_properties( RegisterType PROPERTIES WORKING_DIRECTORY /home/runner/work/aqnwb/aqnwb/build2/tests)
add_test( [==[TimeSeries is registered as a subclass of RegisteredType]==] /home/runner/work/aqnwb/aqnwb/build2/tests/aqnwb_test [==[TimeSeries is registered as a subclass of RegisteredType]==]  )
set_tests_properties( [==[TimeSeries is registered as a subclass of RegisteredType]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/aqnwb/aqnwb/build2/tests)
add_test( TimeSeries /home/runner/work/aqnwb/aqnwb/build2/tests/aqnwb_test TimeSeries  )
set_tests_properties( TimeSeries PROPERTIES WORKING_DIRECTORY /home/runner/work/aqnwb/aqnwb/build2/tests)
add_test( [==[LinkArrayDataSetConfig for TimeSeries data]==] /home/runner/work/aqnwb/aqnwb/build2/tests/aqnwb_test [==[LinkArrayDataSetConfig for TimeSeries data]==]  )
set_tests_properties( [==[LinkArrayDataSetConfig for TimeSeries data]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/aqnwb/aqnwb/build2/tests)
add_test( [==[Test storageObjectTypeToString]==] /home/runner/work/aqnwb/aqnwb/build2/tests/aqnwb_test [==[Test storageObjectTypeToString]==]  )
set_tests_properties( [==[Test storageObjectTypeToString]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/aqnwb/aqnwb/build2/tests)
add_test( [==[Test Status enum operators]==] /home/runner/work/aqnwb/aqnwb/build2/tests/aqnwb_test [==[Test Status enum operators]==]  )
set_tests_properties( [==[Test Status enum operators]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/aqnwb/aqnwb/build2/tests)
add_test( [==[Test IsDataStorageObjectType template]==] /home/runner/work/aqnwb/aqnwb/build2/tests/aqnwb_test [==[Test IsDataStorageObjectType template]==]  )
set_tests_properties( [==[Test IsDataStorageObjectType template]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/aqnwb/aqnwb/build2/tests)
add_test( [==[Test SizeTypeNotSet constant]==] /home/runner/work/aqnwb/aqnwb/build2/tests/aqnwb_test [==[Test SizeTypeNotSet constant]==]  )
set_tests_properties( [==[Test SizeTypeNotSet constant]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/aqnwb/aqnwb/build2/tests)
add_test( [==[isISO8601Date function tests]==] /home/runner/work/aqnwb/aqnwb/build2/tests/aqnwb_test [==[isISO8601Date function tests]==]  )
set_tests_properties( [==[isISO8601Date function tests]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/aqnwb/aqnwb/build2/tests)
add_test( [==[Test UUID generation]==] /home/runner/work/aqnwb/aqnwb/build2/tests/aqnwb_test [==[Test UUID generation]==]  )
set_tests_properties( [==[Test UUID generation]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/aqnwb/aqnwb/build2/tests)
add_test( [==[Test current time format]==] /home/runner/work/aqnwb/aqnwb/build2/tests/aqnwb_test [==[Test current time format]==]  )
set_tests_properties( [==[Test current time format]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/aqnwb/aqnwb/build2/tests)
add_test( [==[Test IO creation]==] /home/runner/work/aqnwb/aqnwb/build2/tests/aqnwb_test [==[Test IO creation]==]  )
set_tests_properties( [==[Test IO creation]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/aqnwb/aqnwb/build2/tests)
add_test( [==[Test path merging]==] /home/runner/work/aqnwb/aqnwb/build2/tests/aqnwb_test [==[Test path merging]==]  )
set_tests_properties( [==[Test path merging]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/aqnwb/aqnwb/build2/tests)
add_test( [==[Test time conversion functions]==] /home/runner/work/aqnwb/aqnwb/build2/tests/aqnwb_test [==[Test time conversion functions]==]  )
set_tests_properties( [==[Test time conversion functions]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/aqnwb/aqnwb/build2/tests)
add_test( [==[Test endian conversion]==] /home/runner/work/aqnwb/aqnwb/build2/tests/aqnwb_test [==[Test endian conversion]==]  )
set_tests_properties( [==[Test endian conversion]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/aqnwb/aqnwb/build2/tests)
add_test( VectorData /home/runner/work/aqnwb/aqnwb/build2/tests/aqnwb_test VectorData  )
set_tests_properties( VectorData PROPERTIES WORKING_DIRECTORY /home/runner/work/aqnwb/aqnwb/build2/tests)
add_test( VectorDataTyped /home/runner/work/aqnwb/aqnwb/build2/tests/aqnwb_test VectorDataTyped  )
set_tests_properties( VectorDataTyped PROPERTIES WORKING_DIRECTORY /home/runner/work/aqnwb/aqnwb/build2/tests)
add_test( [==[LinkArrayDataSetConfig for VectorData]==] /home/runner/work/aqnwb/aqnwb/build2/tests/aqnwb_test [==[LinkArrayDataSetConfig for VectorData]==]  )
set_tests_properties( [==[LinkArrayDataSetConfig for VectorData]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/aqnwb/aqnwb/build2/tests)
add_test( SWMRmodeExamples /home/runner/work/aqnwb/aqnwb/build2/tests/aqnwb_test SWMRmodeExamples  )
set_tests_properties( SWMRmodeExamples PROPERTIES WORKING_DIRECTORY /home/runner/work/aqnwb/aqnwb/build2/tests)
add_test( HDF5FiltersExamples /home/runner/work/aqnwb/aqnwb/build2/tests/aqnwb_test HDF5FiltersExamples  )
set_tests_properties( HDF5FiltersExamples PROPERTIES WORKING_DIRECTORY /home/runner/work/aqnwb/aqnwb/build2/tests)
add_test( SimpleExamples /home/runner/work/aqnwb/aqnwb/build2/tests/aqnwb_test SimpleExamples  )
set_tests_properties( SimpleExamples PROPERTIES WORKING_DIRECTORY /home/runner/work/aqnwb/aqnwb/build2/tests)
add_test( workflowExamples /home/runner/work/aqnwb/aqnwb/build2/tests/aqnwb_test workflowExamples  )
set_tests_properties( workflowExamples PROPERTIES WORKING_DIRECTORY /home/runner/work/aqnwb/aqnwb/build2/tests)
add_test( ElectricalSeriesReadExample /home/runner/work/aqnwb/aqnwb/build2/tests/aqnwb_test ElectricalSeriesReadExample  )
set_tests_properties( ElectricalSeriesReadExample PROPERTIES WORKING_DIRECTORY /home/runner/work/aqnwb/aqnwb/build2/tests)
add_test( LinkTimeSeriesExamples /home/runner/work/aqnwb/aqnwb/build2/tests/aqnwb_test LinkTimeSeriesExamples  )
set_tests_properties( LinkTimeSeriesExamples PROPERTIES WORKING_DIRECTORY /home/runner/work/aqnwb/aqnwb/build2/tests)
add_test( [==[RegisterType Example]==] /home/runner/work/aqnwb/aqnwb/build2/tests/aqnwb_test [==[RegisterType Example]==]  )
set_tests_properties( [==[RegisterType Example]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/aqnwb/aqnwb/build2/tests)
add_test( [==[RegisterType Templated Example]==] /home/runner/work/aqnwb/aqnwb/build2/tests/aqnwb_test [==[RegisterType Templated Example]==]  )
set_tests_properties( [==[RegisterType Templated Example]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/aqnwb/aqnwb/build2/tests)
set( aqnwb_test_TESTS [==[Test ArrayDataSetConfig]==] [==[BaseDataType equality operator]==] [==[BaseDataType fromTypeId]==] [==[Test findTypes and getFullTypeName]==] [==[Test BaseArrayDataSetConfig polymorphism]==] [==[Test LinkArrayDataSetConfig]==] [==[Test LinkArrayDataSetConfig::validateTarget]==] [==[Test Channel Construction and Basic Operations]==] [==[Test Channel Setters]==] [==[Test Channel Copy and Move Operations]==] Data DataTyped Device DynamicTable [==[registered ecephys types]==] ElectricalSeries SpikeEventSeries ElementIdentifiers ElectrodesTable [==[open - hdf5 file modes]==] createGroup getStorageObjects getStorageObjectShape HDF5IO [==[ write datasets]==] [==[HDF5IO createArrayDataSet with filters]==] HDF5IO [==[ create attributes]==] HDF5IO [==[ SWMR mode]==] getH5ObjectType getNativeType getH5Type objectExists HDF5IOI::attributeExists getStorageObjectType readAttribute HDF5IO [==[ read dataset]==] HDF5IO [==[ read dataset subset]==] [==[Test HDF5IO createArrayDataSet with LinkArrayDataSetConfig]==] getStorageObjectDataType [==[HDF5FilterConfig constructor]==] [==[HDF5FilterConfig factory methods]==] [==[HDF5ArrayDataSetConfig addFilter]==] [==[HDF5RecordingData basic operations]==] [==[HDF5RecordingData write operations]==] [==[HDF5RecordingData multi-dimensional operations]==] AnnotationSeries [==[Test NamespaceRegistry]==] [==[NWBFile registered]==] saveNWBFile initialize createElectrodesTable createElectricalSeriesWithSubsetOfElectrodes createElectricalSeriesFailsWithoutElectrodesTable createElectricalSeriesFailsWithOutOfRangeIndices createElectricalSeries createMultipleEcephysDatasets createAnnotationSeries setCanModifyObjectsMode testAttributeAndDatasetFields [==[ProcessingModule registered]==] createProcessingModule createMultipleProcessingModules [==[ProcessingModule createNWBDataInterface and readNWBDataInterface]==] [==[ProcessingModule createDynamicTable and readDynamicTable]==] [==[ProcessingModule initialize fails when IO is deleted]==] [==[DataBlock - Basic Functionality]==] [==[DataBlockGeneric - Basic Functionality]==] [==[DataBlock - Edge Cases]==] [==[DataBlockGeneric - as_variant Method]==] [==[DataBlockGeneric - Compute Mean with std::visit]==] [==[ConstMultiArrayView - Basic Functionality]==] [==[DataBlock - as_multi_array]==] ReadDataWrapper [==[ introspection methods]==] writeContinuousData [==[RecordingObjects recording workflow tests]==] RegisterType [==[TimeSeries is registered as a subclass of RegisteredType]==] TimeSeries [==[LinkArrayDataSetConfig for TimeSeries data]==] [==[Test storageObjectTypeToString]==] [==[Test Status enum operators]==] [==[Test IsDataStorageObjectType template]==] [==[Test SizeTypeNotSet constant]==] [==[isISO8601Date function tests]==] [==[Test UUID generation]==] [==[Test current time format]==] [==[Test IO creation]==] [==[Test path merging]==] [==[Test time conversion functions]==] [==[Test endian conversion]==] VectorData VectorDataTyped [==[LinkArrayDataSetConfig for VectorData]==] SWMRmodeExamples HDF5FiltersExamples SimpleExamples workflowExamples ElectricalSeriesReadExample LinkTimeSeriesExamples [==[RegisterType Example]==] [==[RegisterType Templated Example]==])
