#include "nwb/hdmf/base/Data.hpp"

using namespace AQNWB::NWB;

// Register the base Data class
REGISTER_SUBCLASS_IMPL(Data)

/** Constructor */
Data::Data(const std::string& path, std::shared_ptr<AQNWB::IO::BaseIO> io)
    : RegisteredType(path, io)
{
}

Status Data::initialize(const IO::BaseArrayDataSetConfig& dataConfig)
{
  auto ioPtr = getIO();
  if (ioPtr == nullptr) {
    std::cerr << "IO object has been deleted. Can't initialize Data: " << m_path
              << std::endl;
    return Status::Failure;
  }

  // Create the dataset or link
  try {
    auto dataset = ioPtr->createArrayDataSet(dataConfig, this->m_path);
    // Note: dataset may be nullptr for links; this is not an error.
  } catch (const std::runtime_error& e) {
    std::cerr << "Data::initialize: Failed to create dataset: " << e.what()
              << std::endl;
    return Status::Failure;
  }

  if (dataConfig.isLink()) {
    // For links, we don't set attributes since there is no dataset to attach
    // them to.
    // TODO: Validate that the target of the link has the appropriate attributes
    // set.
    return Status::Success;
  } else {
    // setup common attributes
    Status commonAttrsStatus = ioPtr->createCommonNWBAttributes(
        m_path, this->getNamespace(), this->getTypeName());
    std::cerr << "commonAttrsStatus: " << commonAttrsStatus << std::endl;
    return commonAttrsStatus;
  }
  return Status::Success;
}

namespace AQNWB::NWB
{

// Explicitly instantiate the DataTyped template for all common data types.
// This ensures that these specializations are generated by the compiler,
// reducing compile times and ensuring availability throughout the program.
template class DataTyped<std::any>;
template class DataTyped<uint8_t>;
template class DataTyped<uint16_t>;
template class DataTyped<uint32_t>;
template class DataTyped<uint64_t>;
template class DataTyped<int8_t>;
template class DataTyped<int16_t>;
template class DataTyped<int32_t>;
template class DataTyped<int64_t>;
template class DataTyped<float>;
template class DataTyped<double>;
template class DataTyped<std::string>;
}  // namespace AQNWB::NWB
