name: Demo - Inspect Electrical Series

permissions:
  contents: read

on:
  push:
    branches:
    - main
  pull_request:
  workflow_dispatch:

jobs:
  build-demo:
    defaults:
      run:
        shell: bash
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.os }}
      cancel-in-progress: true
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies - ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libhdf5-dev libcurl4-openssl-dev
        git clone https://github.com/catchorg/Catch2.git
        cd Catch2
        git checkout "v3.5.3"
        cmake -Bbuild -H. -DBUILD_TESTING=OFF
        sudo cmake --build build/ --target install

    - name: Configure and build the main project
      shell: pwsh
      run: |
        cmake "--preset=ci-$("${{ matrix.os }}".split("-")[0])" -DAQNWB_USE_REMFILE=ON
        cmake --build build --config Release -j 2

    - name: Install aqnwb
      run: cmake --install build --prefix ${{ github.workspace }}/install

    # Run the test suite to generate test files. Alternatively we
    # could have the workflow depend on the unit test workflow and
    # download its artifacts, but its simple enough to just run the tests
    # - name: Download test data artifact
    #   uses: actions/download-artifact@v4
    #   with:
    #     name: test-files-macos-latest
    #     path: build/tests/data
    - name: Run AqNWB unit tests
      working-directory: build
      run: ctest --output-on-failure --no-tests=error -C Release -j 2

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: aqnwb-demo
        environment-file: demo/remote_read_benchmark/conda-env.yml 
      if: matrix.os == 'ubuntu-latest'

    - name: Build the inspect_electrical_series demo - ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: |
        cd demo/inspect_electrical_series
        cmake -B build -S . -DCMAKE_PREFIX_PATH="${{ github.workspace }}/install"
        cmake --build build --config Release -j 2

    - name: Run the inspect_electrical_series demo - ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: |
        cd demo/inspect_electrical_series/build/bin
        ./nwb_analysis_demo ../../../../build/tests/data/createElectricalSeries.nwb

    - name: Build the labmetadata_extension_demo demo - ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: |
        cd demo/labmetadata_extension_demo
        cmake -B build -S . -DCMAKE_PREFIX_PATH="${{ github.workspace }}/install"
        cmake --build build --config Release -j 2

    - name: Run the labmetadata_extension_demo demo - ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: |
        cd demo/labmetadata_extension_demo/build/bin
        ./labmetadata_extension_demo

    - name: Build the remote_read_benchmark demo - ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: |
        cd demo/remote_read_benchmark
        cmake -B build -S . -DCMAKE_PREFIX_PATH="${{ github.workspace }}/install"
        cmake --build build --config Release -j 2

    - name: Run the remote_read_benchmark demo - ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: |
        cd demo/remote_read_benchmark/build/bin
        ./remote_read_benchmark \
            "https://dandiarchive.s3.amazonaws.com/blobs/fec/8a6/fec8a690-2ece-4437-8877-8a002ff8bd8a" \
            "us-east-2" \
            "ElectricalSeriesAp" \
            "0,0" \
            "10,1"

    - name: Run the remote_read_benchmark demo with the remfile driver - ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: |
        cd demo/remote_read_benchmark/build/bin
        ./remote_read_benchmark \
            "https://dandiarchive.s3.amazonaws.com/blobs/fec/8a6/fec8a690-2ece-4437-8877-8a002ff8bd8a" \
            "us-east-2" \
            "ElectricalSeriesAp" \
            "0,0" \
            "10,1" \
            remfile

    - name: Run the remote_read_benchmark Python benchmark (ROS3) - ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: |
        conda run -n aqnwb-demo python demo/remote_read_benchmark/benchmark.py \
            "https://dandiarchive.s3.amazonaws.com/blobs/fec/8a6/fec8a690-2ece-4437-8877-8a002ff8bd8a" \
            "us-east-2" \
            "ElectricalSeriesAp" \
            "0,0" \
            "10,1"

    - name: Run the remote_read_benchmark Python benchmark (remfile) - ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: |
        conda run -n aqnwb-demo python demo/remote_read_benchmark/benchmark.py \
            "https://dandiarchive.s3.amazonaws.com/blobs/fec/8a6/fec8a690-2ece-4437-8877-8a002ff8bd8a" \
            "us-east-2" \
            "ElectricalSeriesAp" \
            "0,0" \
            "10,1" \
            --force-remfile

