name: Codespell

on:
  push:
    branches:
    - main

  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  codespell:
    name: Check for spelling errors
    runs-on: ubuntu-latest
    steps:
        - name: Checkout repository
          uses: actions/checkout@v4
        - name: Codespell
          uses: codespell-project/actions-codespell@v2
