name: Doxygen build test

on:
  pull_request:
    #branches:
    #- main

jobs:
  test:
    defaults:
      run:
        shell: bash

    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: "true"

      - name: Install dependencies - macos
        run: brew install hdf5 boost catch2 doxygen graphviz

      - name: Configure
        shell: pwsh
        run: cmake "--preset=ci-macos" "-DFAIL_ON_WARNINGS=ON"

      - name: Build
        run: cmake --build build

      - name: Build the docs
        run : cmake "-DPROJECT_SOURCE_DIR=$PWD" "-DPROJECT_BINARY_DIR=$PWD/build" -P cmake/docs-ci.cmake